//! `gnxas` vs larch's module-level `gnxas` (the documented, working form).
//!
//! Reference generated by `scripts/ref_gnxas.py`. larch's asteval-injected
//! `gnxas` is broken upstream (raises on an undefined name), so there is no
//! stock-larch end-to-end feffit reference; the module-level function is the
//! numerically-identical documented implementation.

use feffit::feffdat::gnxas;
use std::path::PathBuf;

fn data(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/data")
        .join(name)
}

#[test]
fn gnxas_matches_larch() {
    let text = std::fs::read_to_string(data("ref_gnxas.txt")).unwrap();
    let mut max_rel = 0.0f64;
    let mut n = 0;
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut it = line.split_whitespace();
        let r0: f64 = it.next().unwrap().parse().unwrap();
        let sigma: f64 = it.next().unwrap().parse().unwrap();
        let beta: f64 = it.next().unwrap().parse().unwrap();
        let reff: f64 = it.next().unwrap().parse().unwrap();
        let want: f64 = it.next().unwrap().parse().unwrap();
        let got = gnxas(r0, sigma, beta, reff);
        let rel = (got - want).abs() / want.abs();
        assert!(
            rel < 1e-12,
            "gnxas({r0}, {sigma}, {beta}, {reff}) = {got}, want {want}, rel {rel:e}"
        );
        max_rel = max_rel.max(rel);
        n += 1;
    }
    assert!(n >= 7, "parsed too few rows: {n}");
    eprintln!("gnxas: {n} points, max rel err {max_rel:e}");
}
