//! End-to-end parity for `feffit::feffit` against larch's `feffit()`.
//!
//! Reads `tests/data/ref_feffit_fit.txt` (generated by
//! `scripts/ref_feffit_fit.py`, which drives the real `larch.xafs.feffit`
//! minimiser), reconstructs the identical two-path Cu fit (same synthesized
//! data, transform, path-parameter wiring, and starting variables), runs the
//! Rust fit, and compares the best-fit values, uncertainties, and statistics.
//!
//! The minimiser is the MINPACK `lmdif` port; larch's path runs the original
//! FORTRAN MINPACK via scipy, so best-fit values agree to ULP-drift level
//! (~1e-7 rel), not bit-for-bit.

use std::collections::HashMap;
use std::path::PathBuf;

use feffdat::FeffPath;
use feffit::{
    DataSet, FeffitResult, FitDataSet, FitSpace, PathSpec, Spec, Transform, XafsOutput, feffit,
};
use params::Parameters;
use xafsft::Window;

fn data_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/data")
}

struct Ref {
    transform: HashMap<String, String>,
    /// k-weight list from a `#kweights a b c` line; empty when the reference
    /// only carries a scalar `#transform kweight N` (single-k-weight fit).
    kweights: Vec<i32>,
    vars: Vec<(String, f64)>, // (name, init) in declaration order
    /// `#bound name min max` lines: variables that carry min/max bounds.
    bounds: HashMap<String, (f64, f64)>,
    stats: HashMap<String, f64>,
    best: Vec<(String, f64, f64)>,    // (name, value, stderr)
    derived: Vec<(String, f64, f64)>, // (name, value, stderr)
    /// `#bkg idx value stderr` — refined-background spline coefficients in index
    /// order (their larch names carry an opaque hashkey, so compare by position).
    bkg: Vec<(usize, f64, f64)>,
    // (dataset, path, name, value, stderr); stderr is NaN for constant specs
    path_params: Vec<(usize, usize, String, f64, f64)>,
    fitspace: String,
    epsilon_k: f64,
    blocks: HashMap<String, Vec<f64>>,
}

impl Ref {
    fn load_named(name: &str) -> Ref {
        let text = std::fs::read_to_string(data_dir().join(name)).unwrap();
        let mut transform = HashMap::new();
        let mut kweights: Vec<i32> = Vec::new();
        let mut vars = Vec::new();
        let mut bounds: HashMap<String, (f64, f64)> = HashMap::new();
        let mut stats = HashMap::new();
        let mut best = Vec::new();
        let mut derived = Vec::new();
        let mut bkg: Vec<(usize, f64, f64)> = Vec::new();
        let mut path_params = Vec::new();
        let mut blocks: HashMap<String, Vec<f64>> = HashMap::new();
        let mut fitspace = String::new();
        let mut epsilon_k = 0.0;
        let mut cur: Option<String> = None;
        for line in text.lines() {
            if let Some(rest) = line.strip_prefix("#fitspace ") {
                fitspace = rest.trim().to_string();
            } else if let Some(rest) = line.strip_prefix("#transform ") {
                let mut it = rest.split_whitespace();
                transform.insert(
                    it.next().unwrap().to_string(),
                    it.next().unwrap().to_string(),
                );
            } else if let Some(rest) = line.strip_prefix("#kweights ") {
                kweights = rest
                    .split_whitespace()
                    .map(|t| t.parse().unwrap())
                    .collect();
            } else if let Some(rest) = line.strip_prefix("#epsilon_k ") {
                epsilon_k = rest.trim().parse().unwrap();
            } else if let Some(rest) = line.strip_prefix("#var ") {
                let mut it = rest.split_whitespace();
                let name = it.next().unwrap().to_string();
                vars.push((name, it.next().unwrap().parse().unwrap()));
            } else if let Some(rest) = line.strip_prefix("#bound ") {
                let mut it = rest.split_whitespace();
                let name = it.next().unwrap().to_string();
                let lo: f64 = it.next().unwrap().parse().unwrap();
                let hi: f64 = it.next().unwrap().parse().unwrap();
                bounds.insert(name, (lo, hi));
            } else if let Some(rest) = line.strip_prefix("#best ") {
                let mut it = rest.split_whitespace();
                let name = it.next().unwrap().to_string();
                let v: f64 = it.next().unwrap().parse().unwrap();
                let s: f64 = it.next().unwrap().parse().unwrap();
                best.push((name, v, s));
            } else if let Some(rest) = line.strip_prefix("#derived ") {
                let mut it = rest.split_whitespace();
                let name = it.next().unwrap().to_string();
                let v: f64 = it.next().unwrap().parse().unwrap();
                let s: f64 = it.next().unwrap().parse().unwrap();
                derived.push((name, v, s));
            } else if let Some(rest) = line.strip_prefix("#bkg ") {
                let mut it = rest.split_whitespace();
                let idx: usize = it.next().unwrap().parse().unwrap();
                let v: f64 = it.next().unwrap().parse().unwrap();
                let s: f64 = it.next().unwrap().parse().unwrap();
                bkg.push((idx, v, s));
            } else if let Some(rest) = line.strip_prefix("#pathparam ") {
                let mut it = rest.split_whitespace();
                let di: usize = it.next().unwrap().parse().unwrap();
                let pi: usize = it.next().unwrap().parse().unwrap();
                let name = it.next().unwrap().to_string();
                let v: f64 = it.next().unwrap().parse().unwrap();
                let s: f64 = it.next().unwrap().parse().unwrap();
                path_params.push((di, pi, name, v, s));
            } else if let Some(name) = line.strip_prefix("#begin ") {
                cur = Some(name.to_string());
                blocks.insert(name.to_string(), Vec::new());
            } else if line == "#end" {
                cur = None;
            } else if let Some(ref name) = cur {
                blocks.get_mut(name).unwrap().push(line.parse().unwrap());
            } else if let Some(rest) = line.strip_prefix('#') {
                // remaining "#key val" scalar statistics
                let mut it = rest.split_whitespace();
                if let (Some(k), Some(v)) = (it.next(), it.next())
                    && let Ok(f) = v.parse::<f64>()
                {
                    stats.insert(k.to_string(), f);
                }
            }
        }
        Ref {
            transform,
            kweights,
            vars,
            bounds,
            stats,
            best,
            derived,
            bkg,
            path_params,
            fitspace,
            epsilon_k,
            blocks,
        }
    }

    fn tf(&self, k: &str) -> f64 {
        self.transform[k].parse().unwrap()
    }
    fn ti(&self, k: &str) -> i32 {
        self.transform[k].parse().unwrap()
    }
    fn ts(&self, k: &str) -> &str {
        &self.transform[k]
    }

    fn transform(&self) -> Transform {
        let fitspace = match self.fitspace.as_str() {
            "r" => FitSpace::R,
            "k" => FitSpace::K,
            "q" => FitSpace::Q,
            "w" => FitSpace::W,
            other => panic!("unknown fitspace {other}"),
        };
        let kweight = if self.kweights.is_empty() {
            vec![self.ti("kweight")]
        } else {
            self.kweights.clone()
        };
        Transform::new(
            self.tf("kmin"),
            self.tf("kmax"),
            kweight,
            self.tf("dk"),
            None,
            Window::from_name(self.ts("window")).unwrap(),
            self.tf("nfft") as usize,
            self.tf("kstep"),
            self.tf("rmin"),
            self.tf("rmax"),
            self.tf("dr"),
            None,
            Window::from_name(self.ts("rwindow")).unwrap(),
            0.0,
            fitspace,
        )
    }
}

/// Build the path with the same wiring as `PATH_WIRING` in the reference
/// script: s02='amp', e0='del_e0', deltar='alpha*reff', sigma2=`sig2_expr`.
fn wired_path(fname: &str, sig2_expr: &str) -> (FeffPath, PathSpec) {
    let path = FeffPath::from_path(data_dir().join(fname)).unwrap();
    let mut spec = PathSpec::defaults(path.feffdat.degen);
    spec.s02 = Spec::Expr("amp".into());
    spec.e0 = Spec::Expr("del_e0".into());
    spec.deltar = Spec::Expr("alpha*reff".into());
    spec.sigma2 = Spec::Expr(sig2_expr.into());
    (path, spec)
}

fn rel(got: f64, want: f64) -> f64 {
    (got - want).abs() / want.abs().max(1e-300)
}

/// `(value, stderr)` of a path parameter from the reference.
fn ref_pathparam(r: &Ref, di: usize, pi: usize, name: &str) -> (f64, f64) {
    r.path_params
        .iter()
        .find(|(d, p, n, _, _)| *d == di && *p == pi && n == name)
        .map(|(_, _, _, v, s)| (*v, *s))
        .unwrap_or_else(|| panic!("path param {di}/{pi}/{name} not in reference"))
}

/// Build the identical two-path Cu fit described by a reference file (same data,
/// transform, path wiring, starting variables, and the `alpha_x10` derived
/// parameter) and run the Rust `feffit`. Shared by the single- and
/// multi-k-weight parity tests, which differ only in the reference's `kweight`.
fn build_and_fit(ref_name: &str) -> (Ref, FeffitResult) {
    let r = Ref::load_named(ref_name);

    let (p1, s1) = wired_path("feff0001.dat", "sig2_1");
    let (p2, s2) = wired_path("feff0002.dat", "sig2_2");

    let dataset = DataSet::new(
        r.blocks["data_k"].clone(),
        r.blocks["data_chi"].clone(),
        vec![p1, p2],
        r.transform(),
    );
    let mut fds = vec![FitDataSet {
        dataset,
        specs: vec![s1, s2],
        epsilon_k: Some(r.epsilon_k),
    }];

    let mut params = Parameters::new();
    for (name, init) in &r.vars {
        params.add_var(name, *init);
    }
    // global constraint parameter, mirroring `DERIVED` in the reference script —
    // unused by any path, present to exercise derived-parameter uncertainty.
    params.add_expr("alpha_x10", "alpha*10");

    let res = feffit(&mut params, &mut fds).expect("feffit");
    (r, res)
}

/// Assert the Rust fit matches the larch reference: structural counts exact,
/// statistics / best-fit values / propagated uncertainties to the lmdif
/// ULP-drift tolerances.
fn assert_two_path_parity(r: &Ref, res: &FeffitResult) {
    // ---- structural counts: exact ----
    assert_eq!(res.nvarys, r.stats["nvarys"] as usize, "nvarys");
    assert_eq!(res.nfree, r.stats["nfree"] as usize, "nfree");
    assert_eq!(res.ndata, r.stats["ndata"] as usize, "ndata");
    assert_eq!(res.nfev, r.stats["nfev"] as i32, "nfev");
    assert!(
        res.info >= 1 && res.info <= 4,
        "info={} not converged",
        res.info
    );

    // ---- statistics: n_idp is pure arithmetic (tight); the rest carry the
    // lmdif ULP drift through chi_square ----
    println!(
        "nfev={} info={} chi2={:.8e} red={:.8e} rfac={:.4e} aic={:.6} bic={:.6}",
        res.nfev, res.info, res.chi_square, res.chi2_reduced, res.rfactor, res.aic, res.bic
    );
    assert!(rel(res.n_idp, r.stats["n_idp"]) < 1e-12, "n_idp");
    assert!(
        rel(res.chi_square, r.stats["chi_square"]) < 1e-6,
        "chi_square"
    );
    assert!(
        rel(res.chi2_reduced, r.stats["chi2_reduced"]) < 1e-6,
        "chi2_reduced"
    );
    assert!(rel(res.rfactor, r.stats["rfactor"]) < 1e-6, "rfactor");
    // aic/bic involve log; absolute tolerance is appropriate
    assert!(
        (res.aic - r.stats["aic"]).abs() < 1e-4,
        "aic {} vs {}",
        res.aic,
        r.stats["aic"]
    );
    assert!(
        (res.bic - r.stats["bic"]).abs() < 1e-4,
        "bic {} vs {}",
        res.bic,
        r.stats["bic"]
    );

    // ---- best-fit values + uncertainties ----
    assert_eq!(res.best.len(), r.best.len());
    for (got, (name, val, std)) in res.best.iter().zip(&r.best) {
        assert_eq!(&got.name, name, "var order");
        println!(
            "{name:8} value got={:.8e} want={:.8e} (rel {:.2e}) | stderr got={:.6e} want={:.6e} (rel {:.2e})",
            got.value,
            val,
            rel(got.value, *val),
            got.stderr,
            std,
            rel(got.stderr, *std)
        );
        assert!(rel(got.value, *val) < 1e-6, "{name} value");
        assert!(rel(got.stderr, *std) < 1e-4, "{name} stderr");
    }

    // ---- derived (global constraint) parameters: value + propagated stderr ----
    assert_eq!(res.derived.len(), r.derived.len(), "derived count");
    for (got, (name, val, std)) in res.derived.iter().zip(&r.derived) {
        assert_eq!(&got.name, name, "derived order");
        println!(
            "derived {name:8} value got={:.8e} want={:.8e} (rel {:.2e}) | stderr got={:.6e} want={:.6e} (rel {:.2e})",
            got.value,
            val,
            rel(got.value, *val),
            got.stderr,
            std,
            rel(got.stderr, *std)
        );
        assert!(rel(got.value, *val) < 1e-6, "derived {name} value");
        assert!(rel(got.stderr, *std) < 1e-4, "derived {name} stderr");
    }

    // ---- path parameters: value (all) + propagated stderr (when larch
    // reports one; a constant spec has no expr → larch None, Rust 0) ----
    assert_eq!(
        res.path_params.len(),
        r.path_params.len(),
        "path-param count"
    );
    let mut got_map: HashMap<(usize, usize, String), (f64, f64)> = HashMap::new();
    for pp in &res.path_params {
        got_map.insert(
            (pp.dataset, pp.path, pp.name.clone()),
            (pp.value, pp.stderr),
        );
    }
    for (di, pi, name, val, std) in &r.path_params {
        let (gv, gs) = got_map[&(*di, *pi, name.clone())];
        println!(
            "path {di}/{pi} {name:7} value got={:.8e} want={:.8e} (rel {:.2e}) | stderr got={:.6e} want={:.6e}",
            gv,
            val,
            rel(gv, *val),
            gs,
            std
        );
        assert!(rel(gv, *val) < 1e-6, "path {di}/{pi} {name} value");
        if std.is_finite() {
            assert!(rel(gs, *std) < 1e-4, "path {di}/{pi} {name} stderr");
        } else {
            assert_eq!(gs, 0.0, "path {di}/{pi} {name} constant stderr");
        }
    }
}

#[test]
fn feffit_matches_larch() {
    let (r, res) = build_and_fit("ref_feffit_fit.txt");
    assert_two_path_parity(&r, &res);
}

/// Same two-path Cu fit, but with a *list-valued* k-weight (`kweight=[1,2,3]`):
/// the residual is the per-k-weight residuals concatenated, so `ndata` is three
/// times the single-k-weight length while `n_idp` is unchanged. Every best-fit
/// value, uncertainty, and statistic must still match larch's `feffit()`.
#[test]
fn feffit_multikw_matches_larch() {
    let (r, res) = build_and_fit("ref_feffit_multikw.txt");
    // multi-k-weight invariants: ndata = 3 × the single-k-weight block (larch
    // reports 312 = 3 × 104), n_idp unchanged (asserted inside the shared parity
    // against the reference's #n_idp).
    assert_eq!(res.ndata, r.stats["ndata"] as usize, "ndata (3 k-weights)");
    assert_eq!(res.ndata % 3, 0, "ndata divisible by the 3 k-weights");
    assert_two_path_parity(&r, &res);
}

/// Same two-path Cu fit, but three of the five variables (`amp`, `sig2_1`,
/// `sig2_2`) carry min/max bounds while `del_e0`/`alpha` stay unbounded. lmfit
/// optimises in internal (unbounded) coordinates and maps back through the
/// Minuit transform; the Rust port does the same, so the whole trajectory
/// (hence `nfev`) and the gradient-scaled uncertainties must match larch. The
/// bounds are inactive (interior solution), isolating the bound machinery.
#[test]
fn feffit_bounds_matches_larch() {
    let r = Ref::load_named("ref_feffit_bounds.txt");

    let (p1, s1) = wired_path("feff0001.dat", "sig2_1");
    let (p2, s2) = wired_path("feff0002.dat", "sig2_2");
    let dataset = DataSet::new(
        r.blocks["data_k"].clone(),
        r.blocks["data_chi"].clone(),
        vec![p1, p2],
        r.transform(),
    );
    let mut fds = vec![FitDataSet {
        dataset,
        specs: vec![s1, s2],
        epsilon_k: Some(r.epsilon_k),
    }];

    let mut params = Parameters::new();
    for (name, init) in &r.vars {
        match r.bounds.get(name) {
            Some(&(lo, hi)) => params.add_var_bounded(name, *init, lo, hi),
            None => params.add_var(name, *init),
        }
    }
    params.add_expr("alpha_x10", "alpha*10");

    let res = feffit(&mut params, &mut fds).expect("feffit");

    assert_two_path_parity(&r, &res);

    // every bounded best-fit value must lie within its bounds
    for (name, &(lo, hi)) in &r.bounds {
        let b = res.best.iter().find(|b| &b.name == name).unwrap();
        assert!(
            b.value >= lo && b.value <= hi,
            "bounded var {name} = {} outside [{lo}, {hi}]",
            b.value
        );
    }
}

/// Two-dataset *simultaneous* fit (one path each, shared transform): the five
/// global variables are shared, but `amp`/`del_e0`/`alpha` couple both datasets
/// while `sig2_1`/`sig2_2` feed one path each. Exercises the multi-dataset
/// aggregation in `feffit` — residual concatenation across datasets, `n_idp`
/// summed (`ndata` = 208 = 2×104, `n_idp` ≈ 2×13.223), and shared-variable
/// coupling — which the single-dataset tests never reached. Parity vs larch's
/// `feffit(params, [ds0, ds1])`.
#[test]
fn feffit_multidataset_matches_larch() {
    let r = Ref::load_named("ref_feffit_multidataset.txt");

    // dataset 0: feff0001 with σ² = sig2_1; dataset 1: feff0002 with σ² = sig2_2.
    let (p0, s0) = wired_path("feff0001.dat", "sig2_1");
    let (p1, s1) = wired_path("feff0002.dat", "sig2_2");
    let ds0 = DataSet::new(
        r.blocks["data_k_0"].clone(),
        r.blocks["data_chi_0"].clone(),
        vec![p0],
        r.transform(),
    );
    let ds1 = DataSet::new(
        r.blocks["data_k_1"].clone(),
        r.blocks["data_chi_1"].clone(),
        vec![p1],
        r.transform(),
    );
    let mut fds = vec![
        FitDataSet {
            dataset: ds0,
            specs: vec![s0],
            epsilon_k: Some(r.epsilon_k),
        },
        FitDataSet {
            dataset: ds1,
            specs: vec![s1],
            epsilon_k: Some(r.epsilon_k),
        },
    ];

    let mut params = Parameters::new();
    for (name, init) in &r.vars {
        params.add_var(name, *init);
    }
    params.add_expr("alpha_x10", "alpha*10");

    let res = feffit(&mut params, &mut fds).expect("feffit");

    // multi-dataset invariants: ndata is the sum over datasets (2×104), and each
    // path parameter carries its dataset index (8 per path × 2 datasets = 16).
    assert_eq!(res.ndata, r.stats["ndata"] as usize, "ndata (2 datasets)");
    assert_eq!(res.ndata % 2, 0, "ndata divisible by the 2 datasets");
    assert_eq!(res.path_params.len(), 16, "8 path params × 2 datasets");
    assert!(
        res.path_params.iter().any(|p| p.dataset == 1),
        "second dataset's path parameters present"
    );
    assert_two_path_parity(&r, &res);
}

/// Background-refinement parity (`refine_bkg`): the same two-path Cu fit with a
/// refined cubic B-spline background. larch adds `nspline` extra `bkg*` fit
/// variables (here 12), mutates the transform (`rmin → rstep`) and `n_idp`
/// (`1 + 2·rmax·(kmax−kmin)/π`), and subtracts the spline from χ(k) before the
/// model. The data has no real background, so the refined coefficients sit near
/// zero; the test verifies the whole machinery (knots, nspline, the modified
/// counts, the extra variables) against larch.
#[test]
fn feffit_refine_bkg_matches_larch() {
    let r = Ref::load_named("ref_feffit_bkg.txt");

    let (p1, s1) = wired_path("feff0001.dat", "sig2_1");
    let (p2, s2) = wired_path("feff0002.dat", "sig2_2");
    let mut dataset = DataSet::new(
        r.blocks["data_k"].clone(),
        r.blocks["data_chi"].clone(),
        vec![p1, p2],
        r.transform(),
    );
    dataset.enable_refine_bkg();
    let mut fds = vec![FitDataSet {
        dataset,
        specs: vec![s1, s2],
        epsilon_k: Some(r.epsilon_k),
    }];

    let mut params = Parameters::new();
    for (name, init) in &r.vars {
        params.add_var(name, *init);
    }
    params.add_expr("alpha_x10", "alpha*10");

    let res = feffit(&mut params, &mut fds).expect("feffit");

    // structural counts: nspline extra vars, modified ndata/n_idp
    let nspline = r.stats["nspline"] as usize;
    assert_eq!(nspline, 12, "reference nspline");
    assert_eq!(fds[0].dataset.bkg_nspline(), nspline, "rust nspline");
    assert_eq!(
        res.nvarys, r.stats["nvarys"] as usize,
        "nvarys (5 + nspline)"
    );
    assert_eq!(res.nvarys, 5 + nspline, "nvarys = user vars + nspline");
    assert_eq!(res.ndata, r.stats["ndata"] as usize, "ndata");
    assert_eq!(res.nfev, r.stats["nfev"] as i32, "nfev");
    assert!(rel(res.n_idp, r.stats["n_idp"]) < 1e-12, "n_idp");

    // knot vector matches larch's splrep knots exactly
    let knots = &r.blocks["knots"];
    let got_knots = fds[0].dataset.bkg_knots();
    assert_eq!(got_knots.len(), knots.len(), "knot count");
    let kmaxd = got_knots
        .iter()
        .zip(knots)
        .fold(0.0f64, |m, (g, w)| m.max((g - w).abs()));
    assert_eq!(kmaxd, 0.0, "knots differ (max {kmaxd:.3e})");

    // statistics
    assert!(
        rel(res.chi_square, r.stats["chi_square"]) < 1e-6,
        "chi_square"
    );
    assert!(
        rel(res.chi2_reduced, r.stats["chi2_reduced"]) < 1e-6,
        "chi2_reduced"
    );
    assert!(rel(res.rfactor, r.stats["rfactor"]) < 1e-6, "rfactor");

    // the five user variables: value + uncertainty
    for (name, val, std) in &r.best {
        let got = res.best.iter().find(|b| &b.name == name).unwrap();
        println!(
            "{name:8} value got={:.8e} want={:.8e} (rel {:.2e}) | stderr got={:.6e} want={:.6e} (rel {:.2e})",
            got.value,
            val,
            rel(got.value, *val),
            got.stderr,
            std,
            rel(got.stderr, *std)
        );
        assert!(rel(got.value, *val) < 1e-6, "{name} value");
        assert!(rel(got.stderr, *std) < 1e-4, "{name} stderr");
    }

    // derived parameter
    for (name, val, std) in &r.derived {
        let got = res.derived.iter().find(|b| &b.name == name).unwrap();
        assert!(rel(got.value, *val) < 1e-6, "derived {name} value");
        assert!(rel(got.stderr, *std) < 1e-4, "derived {name} stderr");
    }

    // background spline coefficients (compare by index; larch names carry an
    // opaque hashkey). The values are ~1e-6, so use an absolute floor alongside
    // the relative check.
    assert_eq!(r.bkg.len(), nspline, "reference bkg count");
    let mut got_bkg: Vec<&feffit::Best> = res
        .best
        .iter()
        .filter(|b| b.name.starts_with("bkg"))
        .collect();
    got_bkg.sort_by_key(|b| b.name.clone());
    assert_eq!(got_bkg.len(), nspline, "rust bkg count");
    for ((idx, val, std), got) in r.bkg.iter().zip(&got_bkg) {
        println!(
            "bkg{idx:02} value got={:.6e} want={:.6e} | stderr got={:.6e} want={:.6e}",
            got.value, val, got.stderr, std
        );
        assert!(
            (got.value - val).abs() < 1e-9 || rel(got.value, *val) < 1e-5,
            "bkg{idx} value got={} want={val}",
            got.value
        );
        assert!(
            (got.stderr - std).abs() < 1e-9 || rel(got.stderr, *std) < 1e-4,
            "bkg{idx} stderr got={} want={std}",
            got.stderr
        );
    }
}

/// Compare one output array against its reference block by peak-relative max
/// deviation (`max|Δ| / max|want|`), the same metric used for the wavelet
/// residual: it stays meaningful where the array crosses zero.
fn cmp_array(name: &str, got: &[f64], want: &[f64], tol: f64) {
    assert_eq!(got.len(), want.len(), "{name} length");
    let peak = want.iter().fold(0.0f64, |m, v| m.max(v.abs())).max(1e-300);
    let maxd = got
        .iter()
        .zip(want)
        .fold(0.0f64, |m, (g, w)| m.max((g - w).abs()));
    println!(
        "{name:18} len={} peak={:.4e} maxd={:.3e} rel={:.3e}",
        got.len(),
        peak,
        maxd,
        maxd / peak
    );
    assert!(
        maxd / peak < tol,
        "{name}: maxd/peak {:.3e} >= {tol:.0e}",
        maxd / peak
    );
}

/// Compare all eight χ(R)/χ(q) arrays of an [`XafsOutput`] against the
/// `{prefix}_chir_*`/`{prefix}_chiq_*` reference blocks.
fn cmp_xafs(out: &XafsOutput, r: &Ref, prefix: &str, tol: f64) {
    let pairs: [(&str, &Vec<f64>); 8] = [
        ("chir_re", &out.chir_re),
        ("chir_im", &out.chir_im),
        ("chir_mag", &out.chir_mag),
        ("chir_pha", &out.chir_pha),
        ("chiq_re", &out.chiq_re),
        ("chiq_im", &out.chiq_im),
        ("chiq_mag", &out.chiq_mag),
        ("chiq_pha", &out.chiq_pha),
    ];
    for (suffix, got) in pairs {
        let name = format!("{prefix}_{suffix}");
        cmp_array(&name, got, &r.blocks[&name], tol);
    }
}

/// `save_outputs`/`_xafsft` parity: after the two-path Cu fit, forward/back-FT
/// the data, model, and each path χ(k) into χ(R)/χ(q) arrays and compare to
/// larch's `feffit(..., path_outputs=True)` outputs. The data χ(R) is a fixed
/// FFT of the synthesized data (independent of the fit), so it matches to FFT
/// round-off; the model and path arrays carry the best-fit lmdif ULP drift.
#[test]
fn feffit_save_outputs_matches_larch() {
    let r = Ref::load_named("ref_feffit_outputs.txt");

    let (p1, s1) = wired_path("feff0001.dat", "sig2_1");
    let (p2, s2) = wired_path("feff0002.dat", "sig2_2");
    let dataset = DataSet::new(
        r.blocks["data_k"].clone(),
        r.blocks["data_chi"].clone(),
        vec![p1, p2],
        r.transform(),
    );
    let mut fds = vec![FitDataSet {
        dataset,
        specs: vec![s1, s2],
        epsilon_k: Some(r.epsilon_k),
    }];

    let mut params = Parameters::new();
    for (name, init) in &r.vars {
        params.add_var(name, *init);
    }
    params.add_expr("alpha_x10", "alpha*10");

    feffit(&mut params, &mut fds).expect("feffit");
    let out = fds[0].dataset.save_outputs(10.0, true);

    // shared output grids (rstep·arange out to rmax_out; q = linspace(0,kmax+2))
    cmp_array("out_r", &out.data.r, &r.blocks["out_r"], 1e-12);
    cmp_array("out_q", &out.data.q, &r.blocks["out_q"], 1e-12);
    cmp_array("out_r(model)", &out.model.r, &r.blocks["out_r"], 1e-12);
    cmp_array("out_q(model)", &out.model.q, &r.blocks["out_q"], 1e-12);

    // data: fixed FFT of the synthesized χ(k), independent of the fit
    cmp_xafs(&out.data, &r, "data", 1e-9);
    // model + per-path: carry the best-fit ULP drift (values ≈ 1e-7 rel)
    cmp_xafs(&out.model, &r, "model", 1e-5);
    assert_eq!(out.paths.len(), 2, "two path outputs");
    cmp_xafs(&out.paths[0], &r, "path0", 1e-5);
    cmp_xafs(&out.paths[1], &r, "path1", 1e-5);
}

/// End-to-end fit whose σ² is `sigma2_eins(temp, theta)` — verifies the
/// path-bound function context on the value path AND the numerical uncertainty
/// propagation through the opaque function, both against larch (`sigma2_eins`
/// needs no Feff DLL, so larch runs the fit directly).
#[test]
fn feffit_sigma2_eins_matches_larch() {
    let r = Ref::load_named("ref_feffit_sigma2.txt");

    let path = FeffPath::from_path(data_dir().join("feff0001.dat")).unwrap();
    let mut spec = PathSpec::defaults(path.feffdat.degen);
    spec.s02 = Spec::Expr("amp".into());
    spec.e0 = Spec::Expr("del_e0".into());
    spec.sigma2 = Spec::Expr("sigma2_eins(temp, theta)".into());

    let dataset = DataSet::new(
        r.blocks["data_k"].clone(),
        r.blocks["data_chi"].clone(),
        vec![path],
        r.transform(),
    );
    let mut fds = vec![FitDataSet {
        dataset,
        specs: vec![spec],
        epsilon_k: Some(r.epsilon_k),
    }];

    let mut params = Parameters::new();
    params.add_fixed("temp", r.stats["temp"]);
    for (name, init) in &r.vars {
        params.add_var(name, *init);
    }

    let res = feffit(&mut params, &mut fds).expect("feffit");

    assert_eq!(res.nfev, r.stats["nfev"] as i32, "nfev");
    assert_eq!(res.nvarys, r.stats["nvarys"] as usize, "nvarys");
    assert!(
        res.info >= 1 && res.info <= 4,
        "info={} not converged",
        res.info
    );

    for (got, (name, val, std)) in res.best.iter().zip(&r.best) {
        assert_eq!(&got.name, name, "var order");
        println!(
            "{name:8} value got={:.8e} want={:.8e} (rel {:.2e}) | stderr got={:.6e} want={:.6e} (rel {:.2e})",
            got.value,
            val,
            rel(got.value, *val),
            got.stderr,
            std,
            rel(got.stderr, *std)
        );
        assert!(rel(got.value, *val) < 1e-6, "{name} value");
        assert!(rel(got.stderr, *std) < 1e-4, "{name} stderr");
    }

    // path σ²: value + uncertainty propagated through sigma2_eins
    let (sv, ss) = ref_pathparam(&r, 0, 0, "sigma2");
    let got = res
        .path_params
        .iter()
        .find(|p| p.dataset == 0 && p.path == 0 && p.name == "sigma2")
        .unwrap();
    println!(
        "sigma2  value got={:.8e} want={:.8e} (rel {:.2e}) | stderr got={:.6e} want={:.6e} (rel {:.2e})",
        got.value,
        sv,
        rel(got.value, sv),
        got.stderr,
        ss,
        rel(got.stderr, ss)
    );
    assert!(rel(got.value, sv) < 1e-6, "sigma2 value");
    assert!(rel(got.stderr, ss) < 1e-4, "sigma2 stderr");
}

/// Rust-only consistency check for σ² uncertainty propagated through
/// `sigma2_debye`. larch's `sigma2_debye` calls the x86_64 Feff DLL, which will
/// not load on arm64, so there is no larch fit reference here. Instead: fit the
/// (eins-synthesized, noisy) data with `sigma2 = sigma2_debye(temp, thetad)`,
/// then confirm the feffit-reported σ² stderr equals an INDEPENDENT first-order
/// propagation — `|d sigma2_debye/d thetad|` (central difference of
/// `feffdat::sigma2_debye` directly) times `stderr(thetad)` — since σ² depends
/// on `thetad` alone. This validates the `sigma2_debye` dispatch in the fit loop
/// and the numerical propagation wiring without a larch reference.
#[test]
fn feffit_sigma2_debye_propagation_consistent() {
    let r = Ref::load_named("ref_feffit_sigma2.txt");

    let path = FeffPath::from_path(data_dir().join("feff0001.dat")).unwrap();
    let fdat = path.feffdat.clone();
    let mut spec = PathSpec::defaults(path.feffdat.degen);
    spec.s02 = Spec::Expr("amp".into());
    spec.sigma2 = Spec::Expr("sigma2_debye(temp, thetad)".into());

    let dataset = DataSet::new(
        r.blocks["data_k"].clone(),
        r.blocks["data_chi"].clone(),
        vec![path],
        r.transform(),
    );
    let mut fds = vec![FitDataSet {
        dataset,
        specs: vec![spec],
        epsilon_k: Some(r.epsilon_k),
    }];

    let mut params = Parameters::new();
    params.add_fixed("temp", 300.0);
    params.add_var("amp", 0.9);
    params.add_var("thetad", 315.0);

    let res = feffit(&mut params, &mut fds).expect("feffit");
    assert!(
        res.info >= 1 && res.info <= 4,
        "debye fit info={} not converged",
        res.info
    );

    let thetad = res.best.iter().find(|b| b.name == "thetad").unwrap();
    let sigma2 = res
        .path_params
        .iter()
        .find(|p| p.name == "sigma2" && p.path == 0)
        .unwrap();

    // value: reported σ² must equal sigma2_debye at the best thetad
    let val_exp = feffdat::sigma2_debye(300.0, thetad.value, fdat.rnorman, &fdat.geom);
    assert!(rel(sigma2.value, val_exp) < 1e-9, "debye σ² value");

    // stderr: independent single-variable propagation
    let h = 1.0e-3;
    let sp = feffdat::sigma2_debye(300.0, thetad.value + h, fdat.rnorman, &fdat.geom);
    let sm = feffdat::sigma2_debye(300.0, thetad.value - h, fdat.rnorman, &fdat.geom);
    let stderr_exp = ((sp - sm) / (2.0 * h)).abs() * thetad.stderr;
    println!(
        "debye σ²: value={:.8e} thetad={:.4}±{:.4} | stderr got={:.6e} expect={:.6e} (rel {:.2e})",
        sigma2.value,
        thetad.value,
        thetad.stderr,
        sigma2.stderr,
        stderr_exp,
        rel(sigma2.stderr, stderr_exp)
    );
    assert!(
        rel(sigma2.stderr, stderr_exp) < 1e-3,
        "debye σ² stderr propagation"
    );
}
