//! End-to-end parity for `feffit::feffit` against larch's `feffit()`.
//!
//! Reads `tests/data/ref_feffit_fit.txt` (generated by
//! `scripts/ref_feffit_fit.py`, which drives the real `larch.xafs.feffit`
//! minimiser), reconstructs the identical two-path Cu fit (same synthesized
//! data, transform, path-parameter wiring, and starting variables), runs the
//! Rust fit, and compares the best-fit values, uncertainties, and statistics.
//!
//! The minimiser is the MINPACK `lmdif` port; larch's path runs the original
//! FORTRAN MINPACK via scipy, so best-fit values agree to ULP-drift level
//! (~1e-7 rel), not bit-for-bit.

use std::collections::HashMap;
use std::path::PathBuf;

use feffdat::FeffPath;
use feffit::{feffit, DataSet, FitDataSet, FitSpace, PathSpec, Spec, Transform};
use params::Parameters;
use xafsft::Window;

fn data_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/data")
}

struct Ref {
    transform: HashMap<String, String>,
    vars: Vec<(String, f64)>, // (name, init) in declaration order
    stats: HashMap<String, f64>,
    best: Vec<(String, f64, f64)>,    // (name, value, stderr)
    derived: Vec<(String, f64, f64)>, // (name, value, stderr)
    // (dataset, path, name, value, stderr); stderr is NaN for constant specs
    path_params: Vec<(usize, usize, String, f64, f64)>,
    fitspace: String,
    epsilon_k: f64,
    blocks: HashMap<String, Vec<f64>>,
}

impl Ref {
    fn load() -> Ref {
        let text = std::fs::read_to_string(data_dir().join("ref_feffit_fit.txt")).unwrap();
        let mut transform = HashMap::new();
        let mut vars = Vec::new();
        let mut stats = HashMap::new();
        let mut best = Vec::new();
        let mut derived = Vec::new();
        let mut path_params = Vec::new();
        let mut blocks: HashMap<String, Vec<f64>> = HashMap::new();
        let mut fitspace = String::new();
        let mut epsilon_k = 0.0;
        let mut cur: Option<String> = None;
        for line in text.lines() {
            if let Some(rest) = line.strip_prefix("#fitspace ") {
                fitspace = rest.trim().to_string();
            } else if let Some(rest) = line.strip_prefix("#transform ") {
                let mut it = rest.split_whitespace();
                transform.insert(
                    it.next().unwrap().to_string(),
                    it.next().unwrap().to_string(),
                );
            } else if let Some(rest) = line.strip_prefix("#epsilon_k ") {
                epsilon_k = rest.trim().parse().unwrap();
            } else if let Some(rest) = line.strip_prefix("#var ") {
                let mut it = rest.split_whitespace();
                let name = it.next().unwrap().to_string();
                vars.push((name, it.next().unwrap().parse().unwrap()));
            } else if let Some(rest) = line.strip_prefix("#best ") {
                let mut it = rest.split_whitespace();
                let name = it.next().unwrap().to_string();
                let v: f64 = it.next().unwrap().parse().unwrap();
                let s: f64 = it.next().unwrap().parse().unwrap();
                best.push((name, v, s));
            } else if let Some(rest) = line.strip_prefix("#derived ") {
                let mut it = rest.split_whitespace();
                let name = it.next().unwrap().to_string();
                let v: f64 = it.next().unwrap().parse().unwrap();
                let s: f64 = it.next().unwrap().parse().unwrap();
                derived.push((name, v, s));
            } else if let Some(rest) = line.strip_prefix("#pathparam ") {
                let mut it = rest.split_whitespace();
                let di: usize = it.next().unwrap().parse().unwrap();
                let pi: usize = it.next().unwrap().parse().unwrap();
                let name = it.next().unwrap().to_string();
                let v: f64 = it.next().unwrap().parse().unwrap();
                let s: f64 = it.next().unwrap().parse().unwrap();
                path_params.push((di, pi, name, v, s));
            } else if let Some(name) = line.strip_prefix("#begin ") {
                cur = Some(name.to_string());
                blocks.insert(name.to_string(), Vec::new());
            } else if line == "#end" {
                cur = None;
            } else if let Some(ref name) = cur {
                blocks.get_mut(name).unwrap().push(line.parse().unwrap());
            } else if let Some(rest) = line.strip_prefix('#') {
                // remaining "#key val" scalar statistics
                let mut it = rest.split_whitespace();
                if let (Some(k), Some(v)) = (it.next(), it.next()) {
                    if let Ok(f) = v.parse::<f64>() {
                        stats.insert(k.to_string(), f);
                    }
                }
            }
        }
        Ref {
            transform,
            vars,
            stats,
            best,
            derived,
            path_params,
            fitspace,
            epsilon_k,
            blocks,
        }
    }

    fn tf(&self, k: &str) -> f64 {
        self.transform[k].parse().unwrap()
    }
    fn ti(&self, k: &str) -> i32 {
        self.transform[k].parse().unwrap()
    }
    fn ts(&self, k: &str) -> &str {
        &self.transform[k]
    }

    fn transform(&self) -> Transform {
        let fitspace = match self.fitspace.as_str() {
            "r" => FitSpace::R,
            "k" => FitSpace::K,
            "q" => FitSpace::Q,
            other => panic!("unknown fitspace {other}"),
        };
        Transform::new(
            self.tf("kmin"),
            self.tf("kmax"),
            self.ti("kweight"),
            self.tf("dk"),
            None,
            Window::from_name(self.ts("window")).unwrap(),
            self.tf("nfft") as usize,
            self.tf("kstep"),
            self.tf("rmin"),
            self.tf("rmax"),
            self.tf("dr"),
            None,
            Window::from_name(self.ts("rwindow")).unwrap(),
            0.0,
            fitspace,
        )
    }
}

/// Build the path with the same wiring as `PATH_WIRING` in the reference
/// script: s02='amp', e0='del_e0', deltar='alpha*reff', sigma2=`sig2_expr`.
fn wired_path(fname: &str, sig2_expr: &str) -> (FeffPath, PathSpec) {
    let path = FeffPath::from_path(data_dir().join(fname)).unwrap();
    let mut spec = PathSpec::defaults(path.feffdat.degen);
    spec.s02 = Spec::Expr("amp".into());
    spec.e0 = Spec::Expr("del_e0".into());
    spec.deltar = Spec::Expr("alpha*reff".into());
    spec.sigma2 = Spec::Expr(sig2_expr.into());
    (path, spec)
}

fn rel(got: f64, want: f64) -> f64 {
    (got - want).abs() / want.abs().max(1e-300)
}

#[test]
fn feffit_matches_larch() {
    let r = Ref::load();

    let (p1, s1) = wired_path("feff0001.dat", "sig2_1");
    let (p2, s2) = wired_path("feff0002.dat", "sig2_2");

    let dataset = DataSet::new(
        r.blocks["data_k"].clone(),
        r.blocks["data_chi"].clone(),
        vec![p1, p2],
        r.transform(),
    );
    let mut fds = vec![FitDataSet {
        dataset,
        specs: vec![s1, s2],
        epsilon_k: Some(r.epsilon_k),
    }];

    let mut params = Parameters::new();
    for (name, init) in &r.vars {
        params.add_var(name, *init);
    }
    // global constraint parameter, mirroring `DERIVED` in ref_feffit_fit.py —
    // unused by any path, present to exercise derived-parameter uncertainty.
    params.add_expr("alpha_x10", "alpha*10");

    let res = feffit(&mut params, &mut fds).expect("feffit");

    // ---- structural counts: exact ----
    assert_eq!(res.nvarys, r.stats["nvarys"] as usize, "nvarys");
    assert_eq!(res.nfree, r.stats["nfree"] as usize, "nfree");
    assert_eq!(res.ndata, r.stats["ndata"] as usize, "ndata");
    assert_eq!(res.nfev, r.stats["nfev"] as i32, "nfev");
    assert!(
        res.info >= 1 && res.info <= 4,
        "info={} not converged",
        res.info
    );

    // ---- statistics: n_idp is pure arithmetic (tight); the rest carry the
    // lmdif ULP drift through chi_square ----
    println!(
        "nfev={} info={} chi2={:.8e} red={:.8e} rfac={:.4e} aic={:.6} bic={:.6}",
        res.nfev, res.info, res.chi_square, res.chi2_reduced, res.rfactor, res.aic, res.bic
    );
    assert!(rel(res.n_idp, r.stats["n_idp"]) < 1e-12, "n_idp");
    assert!(
        rel(res.chi_square, r.stats["chi_square"]) < 1e-6,
        "chi_square"
    );
    assert!(
        rel(res.chi2_reduced, r.stats["chi2_reduced"]) < 1e-6,
        "chi2_reduced"
    );
    assert!(rel(res.rfactor, r.stats["rfactor"]) < 1e-6, "rfactor");
    // aic/bic involve log; absolute tolerance is appropriate
    assert!(
        (res.aic - r.stats["aic"]).abs() < 1e-4,
        "aic {} vs {}",
        res.aic,
        r.stats["aic"]
    );
    assert!(
        (res.bic - r.stats["bic"]).abs() < 1e-4,
        "bic {} vs {}",
        res.bic,
        r.stats["bic"]
    );

    // ---- best-fit values + uncertainties ----
    assert_eq!(res.best.len(), r.best.len());
    for (got, (name, val, std)) in res.best.iter().zip(&r.best) {
        assert_eq!(&got.name, name, "var order");
        println!(
            "{name:8} value got={:.8e} want={:.8e} (rel {:.2e}) | stderr got={:.6e} want={:.6e} (rel {:.2e})",
            got.value, val, rel(got.value, *val), got.stderr, std, rel(got.stderr, *std)
        );
        assert!(rel(got.value, *val) < 1e-6, "{name} value");
        assert!(rel(got.stderr, *std) < 1e-4, "{name} stderr");
    }

    // ---- derived (global constraint) parameters: value + propagated stderr ----
    assert_eq!(res.derived.len(), r.derived.len(), "derived count");
    for (got, (name, val, std)) in res.derived.iter().zip(&r.derived) {
        assert_eq!(&got.name, name, "derived order");
        println!(
            "derived {name:8} value got={:.8e} want={:.8e} (rel {:.2e}) | stderr got={:.6e} want={:.6e} (rel {:.2e})",
            got.value, val, rel(got.value, *val), got.stderr, std, rel(got.stderr, *std)
        );
        assert!(rel(got.value, *val) < 1e-6, "derived {name} value");
        assert!(rel(got.stderr, *std) < 1e-4, "derived {name} stderr");
    }

    // ---- path parameters: value (all) + propagated stderr (when larch
    // reports one; a constant spec has no expr → larch None, Rust 0) ----
    assert_eq!(
        res.path_params.len(),
        r.path_params.len(),
        "path-param count"
    );
    let mut got_map: HashMap<(usize, usize, String), (f64, f64)> = HashMap::new();
    for pp in &res.path_params {
        got_map.insert(
            (pp.dataset, pp.path, pp.name.clone()),
            (pp.value, pp.stderr),
        );
    }
    for (di, pi, name, val, std) in &r.path_params {
        let (gv, gs) = got_map[&(*di, *pi, name.clone())];
        println!(
            "path {di}/{pi} {name:7} value got={:.8e} want={:.8e} (rel {:.2e}) | stderr got={:.6e} want={:.6e}",
            gv, val, rel(gv, *val), gs, std
        );
        assert!(rel(gv, *val) < 1e-6, "path {di}/{pi} {name} value");
        if std.is_finite() {
            assert!(rel(gs, *std) < 1e-4, "path {di}/{pi} {name} stderr");
        } else {
            assert_eq!(gs, 0.0, "path {di}/{pi} {name} constant stderr");
        }
    }
}
