//! `find_e0` / `find_energy_step` and the math primitives vs `larch`.
//!
//! Reference generated by `scripts/ref_e0.py` on the Cu foil `mu(E)`.

use std::collections::HashMap;
use std::path::PathBuf;

use feffit::xasproc::mathutils::{SmoothForm, polyfit, smooth};
use feffit::xasproc::{find_e0, find_energy_step};

fn data(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/data")
        .join(name)
}

fn load_xmu() -> (Vec<f64>, Vec<f64>) {
    let text = std::fs::read_to_string(data("cu.xmu")).unwrap();
    let mut e = Vec::new();
    let mut m = Vec::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        e.push(it.next().unwrap().parse().unwrap());
        m.push(it.next().unwrap().parse().unwrap());
    }
    (e, m)
}

struct Ref {
    scalars: HashMap<String, f64>,
    polyfit2: [f64; 3],
    smooth: Vec<(usize, f64)>,
}

fn load_ref() -> Ref {
    let text = std::fs::read_to_string(data("ref_e0.txt")).unwrap();
    let mut scalars = HashMap::new();
    let mut polyfit2 = [0.0; 3];
    let mut smooth = Vec::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        match it.next().unwrap() {
            "npts" => {}
            "polyfit2" => {
                for c in polyfit2.iter_mut() {
                    *c = it.next().unwrap().parse().unwrap();
                }
            }
            "smooth" => {
                let i: usize = it.next().unwrap().parse().unwrap();
                let v: f64 = it.next().unwrap().parse().unwrap();
                smooth.push((i, v));
            }
            key => {
                scalars.insert(key.to_string(), it.next().unwrap().parse().unwrap());
            }
        }
    }
    Ref {
        scalars,
        polyfit2,
        smooth,
    }
}

fn rel(g: f64, w: f64) -> f64 {
    (g - w).abs() / w.abs().max(1e-300)
}

#[test]
fn find_energy_step_matches_larch() {
    let (energy, _mu) = load_xmu();
    let r = load_ref();
    let got = find_energy_step(&energy);
    let want = r.scalars["find_energy_step"];
    assert!(rel(got, want) < 1e-12, "estep {got} vs {want}");
}

#[test]
fn find_e0_matches_larch() {
    let (energy, mu) = load_xmu();
    let r = load_ref();
    let got = find_e0(&energy, &mu);
    let want = r.scalars["find_e0"];
    // E0 lands on a grid energy value; require an exact bit match.
    assert_eq!(got, want, "e0 {got} vs {want}");
}

#[test]
fn polyfit_matches_numpy() {
    let (energy, mu) = load_xmu();
    let r = load_ref();
    let c = polyfit(&energy[100..140], &mu[100..140], 2);
    for (k, (&g, &w)) in c.iter().zip(r.polyfit2.iter()).enumerate() {
        assert!(rel(g, w) < 1e-9, "polyfit coef[{k}] {g} vs {w}");
    }
}

#[test]
fn smooth_matches_larch() {
    let (energy, mu) = load_xmu();
    let r = load_ref();
    let dmu = feffit::xasproc::mathutils::dmude(&mu, &energy);
    let sm = smooth(&energy, &dmu, 0.5, 0.5, 5, SmoothForm::Lorentzian);
    for (i, want) in r.smooth {
        let got = sm[i];
        assert!(
            (got - want).abs() < 1e-9 + 1e-7 * want.abs(),
            "smooth[{i}] {got} vs {want}"
        );
    }
}
