//! `feffit::xasproc::xanes` primitives vs `larch` / `lmfit`.
//!
//! Reference generated by `scripts/ref_xanes.py`:
//!   * `peak` / `valley` — larch resolves the region with `index_of` then takes
//!     numpy `argmax`/`argmin` over the inclusive window.
//!   * `arctan_step` — lmfit `StepModel(form='arctan')` (the edge-step shape
//!     larch's `pre_edge_baseline` fits).
//!   * `centroid` — larch `pre_edge_baseline`'s `(edat*peaks).sum()/peaks.sum()`.
//!
//! `x_at_y` is XAFSView's own level-crossing cursor with no larch counterpart, so
//! it has no parity case here (it is covered by unit tests in `src/xanes.rs`).

use std::path::PathBuf;

use feffit::xasproc::{arctan_step, centroid, peak, valley};

fn load() -> std::collections::HashMap<String, Vec<f64>> {
    let path: PathBuf = [env!("CARGO_MANIFEST_DIR"), "tests", "data", "ref_xanes.txt"]
        .iter()
        .collect();
    let text = std::fs::read_to_string(path).expect("read ref_xanes.txt");
    let mut m = std::collections::HashMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut it = line.split_whitespace();
        let key = it.next().unwrap().to_owned();
        m.insert(key, it.map(|t| t.parse::<f64>().unwrap()).collect());
    }
    m
}

#[test]
fn peak_valley_match_larch() {
    let r = load();
    let grid = &r["grid"];
    let y = &r["y"];
    let (lo, hi) = (r["region"][0], r["region"][1]);

    let (pe, pv) = peak(grid, y, lo, hi).expect("peak");
    assert_eq!(pe, r["peak"][0], "peak energy");
    assert!((pv - r["peak"][1]).abs() < 1e-12, "peak value: {pv}");

    let (ve, vv) = valley(grid, y, lo, hi).expect("valley");
    assert_eq!(ve, r["valley"][0], "valley energy");
    assert!((vv - r["valley"][1]).abs() < 1e-12, "valley value: {vv}");
}

#[test]
fn arctan_step_matches_lmfit() {
    let r = load();
    let grid = &r["grid"];
    let (amp, center, sigma) = (
        r["astep_params"][0],
        r["astep_params"][1],
        r["astep_params"][2],
    );
    let got = arctan_step(grid, amp, center, sigma);
    let want = &r["astep"];
    assert_eq!(got.len(), want.len());
    for (i, (g, w)) in got.iter().zip(want).enumerate() {
        assert!((g - w).abs() < 1e-12, "astep[{i}]: {g} vs {w}");
    }
}

#[test]
fn centroid_matches_larch() {
    let r = load();
    let grid = &r["grid"];
    let c = centroid(grid, &r["cweights"]).expect("centroid");
    assert!((c - r["centroid"][0]).abs() < 1e-9, "centroid: {c}");
}
