//! AUTOBK with a standard `chi(k)` background constraint vs `larch`.
//!
//! Reference generated by `scripts/ref_autobk_chistd.py`: larch's `autobk` on
//! the Cu foil `mu(E)` with an analytic first-shell-like standard fed via
//! `k_std`/`chi_std`. The standard (and its 0.1-spaced k grid, distinct from the
//! 0.05 output grid) is stored verbatim in the reference so this test feeds a
//! bit-identical input — the `np.interp(kout, k_std, chi_std)` onto the output
//! grid is exercised exactly as larch does it.

use std::collections::HashMap;
use std::path::PathBuf;

use feffit::xasproc::{AutobkParams, autobk};

fn data(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/data")
        .join(name)
}

fn load_xmu() -> (Vec<f64>, Vec<f64>) {
    let text = std::fs::read_to_string(data("cu.xmu")).unwrap();
    let mut e = Vec::new();
    let mut m = Vec::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        e.push(it.next().unwrap().parse().unwrap());
        m.push(it.next().unwrap().parse().unwrap());
    }
    (e, m)
}

struct Ref {
    scalars: HashMap<String, f64>,
    /// densely-indexed arrays (the standard input + sampled outputs).
    arrays: HashMap<String, Vec<(usize, f64)>>,
}

impl Ref {
    /// Reconstruct a dense `Vec` from a fully-populated array key (`kstd`,
    /// `chistd`), asserting the indices are `0..n` contiguous.
    fn dense(&self, key: &str) -> Vec<f64> {
        let mut pairs = self.arrays[key].clone();
        pairs.sort_by_key(|&(i, _)| i);
        for (n, &(i, _)) in pairs.iter().enumerate() {
            assert_eq!(i, n, "{key} index gap at {n}");
        }
        pairs.into_iter().map(|(_, v)| v).collect()
    }
}

fn load_ref() -> Ref {
    let text = std::fs::read_to_string(data("ref_autobk_chistd.txt")).unwrap();
    let mut scalars = HashMap::new();
    let mut arrays: HashMap<String, Vec<(usize, f64)>> = HashMap::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        let key = it.next().unwrap();
        match key {
            "kstd" | "chistd" | "k" | "chi" | "bkg" | "chie" | "initbkg" | "initchi" => {
                let i: usize = it.next().unwrap().parse().unwrap();
                let v: f64 = it.next().unwrap().parse().unwrap();
                arrays.entry(key.to_string()).or_default().push((i, v));
            }
            _ => {
                scalars.insert(key.to_string(), it.next().unwrap().parse().unwrap());
            }
        }
    }
    Ref { scalars, arrays }
}

fn rel(g: f64, w: f64) -> f64 {
    (g - w).abs() / w.abs().max(1e-300)
}

#[test]
fn autobk_chistd_matches_larch() {
    let (energy, mu) = load_xmu();
    let r = load_ref();
    let k_std = r.dense("kstd");
    let chi_std = r.dense("chistd");
    assert_eq!(k_std.len(), chi_std.len(), "standard length");

    let params = AutobkParams {
        k_std: Some(k_std.clone()),
        chi_std: Some(chi_std.clone()),
        ..AutobkParams::default()
    };
    let ab = autobk(&energy, &mu, &params);

    // integer / structural scalars (exact) — unchanged by the standard, which
    // only enters the fit residual.
    assert_eq!(ab.ek0, r.scalars["ek0"], "ek0");
    assert_eq!(ab.nspl as f64, r.scalars["nspl"], "nspl");
    assert_eq!(ab.irbkg as f64, r.scalars["irbkg"], "irbkg");
    assert_eq!(ab.iek0 as f64, r.scalars["iek0"], "iek0");
    assert_eq!(ab.iemax as f64, r.scalars["iemax"], "iemax");
    assert_eq!(ab.k.len() as f64, r.scalars["nk"], "nk");
    assert_eq!(ab.bkg.len() as f64, r.scalars["nbkg"], "nbkg");
    assert_eq!(ab.rbkg, r.scalars["rbkg"], "rbkg");
    assert!(
        rel(ab.edge_step, r.scalars["edge_step"]) < 1e-10,
        "edge_step {} vs {}",
        ab.edge_step,
        r.scalars["edge_step"]
    );

    let kcheck = |name: &str, arr: &[f64], tol: f64| -> f64 {
        let mut worst = 0.0_f64;
        for &(i, want) in &r.arrays[name] {
            let got = arr[i];
            let d = (got - want).abs();
            worst = worst.max(d);
            assert!(
                d < 1e-12 + tol * want.abs().max(1.0),
                "{name}[{i}] {got} vs {want} (abs {d})"
            );
        }
        worst
    };
    kcheck("k", &ab.k, 1e-12);

    // pre-fit init arrays: larch computes these with `spline_eval` *without* the
    // standard (autobk.py:190), so they match the no-standard case to machine
    // precision.
    let w_initbkg = kcheck("initbkg", &ab.init_bkg, 1e-12);
    let w_initchi = kcheck("initchi", &ab.init_chi, 1e-12);

    // constrained outputs (FITPACK + MINPACK lmdif on the chi_std residual).
    let w_bkg = kcheck("bkg", &ab.bkg, 1e-11);
    let w_chi = kcheck("chi", &ab.chi, 1e-11);
    let w_chie = kcheck("chie", &ab.chie, 1e-11);

    // guard: the standard must actually change the fit. Compare against the
    // no-standard default run — a regression that ignored chi_std would leave
    // these identical.
    let ab0 = autobk(&energy, &mu, &AutobkParams::default());
    let max_chi_diff = ab
        .chi
        .iter()
        .zip(&ab0.chi)
        .map(|(a, b)| (a - b).abs())
        .fold(0.0_f64, f64::max);
    assert!(
        max_chi_diff > 1e-4,
        "chi_std did not change the fit (max |Δchi| = {max_chi_diff:.3e}); \
         the standard constraint was not applied"
    );

    eprintln!(
        "worst abs deltas: initbkg={w_initbkg:.2e} initchi={w_initchi:.2e} \
         bkg={w_bkg:.2e} chi={w_chi:.2e} chie={w_chie:.2e}; \
         vs-no-std max|Δchi|={max_chi_diff:.3e}"
    );
}
