//! PCA (`pca_train` + `pca_fit`) vs `larch` on a synthetic Cu-derived training
//! set. Reference generated by `scripts/ref_pca.py`.
//!
//! Not bit-exact: `eigh`/`lstsq` use nalgebra vs LAPACK (~1e-11). Eigenvector
//! signs are arbitrary, so `components` is compared up to a per-row sign;
//! everything else (`eigenvalues`, `variances`, `ind`, `nsig`, `mean`, and the
//! whole `pca_fit` result) is sign-independent.

use std::collections::HashMap;
use std::path::PathBuf;

use feffit::xasproc::{pca_fit, pca_train};

fn data(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/data")
        .join(name)
}

#[derive(Default)]
struct Ref {
    narr: usize,
    nfreq: usize,
    ncomps: usize,
    nsig: usize,
    ydat: Vec<Vec<f64>>,
    comp: Vec<Vec<f64>>,
    mean: Vec<f64>,
    eigval: Vec<f64>,
    variance: Vec<f64>,
    ind: Vec<f64>,
    unknown: Vec<f64>,
    fit_weight: Vec<f64>,
    fit_yfit: Vec<(usize, f64)>,
    scalars: HashMap<String, f64>,
}

fn load_ref() -> Ref {
    let text = std::fs::read_to_string(data("ref_pca.txt")).unwrap();
    let mut r = Ref::default();
    // first pass: dims
    for line in text.lines() {
        let p: Vec<&str> = line.split_whitespace().collect();
        match p.as_slice() {
            ["narr", v] => r.narr = v.parse().unwrap(),
            ["nfreq", v] => r.nfreq = v.parse().unwrap(),
            ["ncomps", v] => r.ncomps = v.parse().unwrap(),
            ["nsig", v] => r.nsig = v.parse().unwrap(),
            _ => {}
        }
    }
    r.ydat = vec![vec![0.0; r.nfreq]; r.narr];
    r.comp = vec![vec![0.0; r.nfreq]; r.narr];
    r.mean = vec![0.0; r.nfreq];
    r.eigval = vec![0.0; r.narr];
    r.variance = vec![0.0; r.narr];
    r.ind = vec![0.0; r.narr];
    r.unknown = vec![0.0; r.nfreq];
    r.fit_weight = vec![0.0; r.ncomps];

    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let p: Vec<&str> = s.split_whitespace().collect();
        match p.as_slice() {
            [key, val] => {
                if let Ok(v) = val.parse::<f64>() {
                    r.scalars.insert(key.to_string(), v);
                }
            }
            ["ydat", i, j, v] => {
                r.ydat[i.parse::<usize>().unwrap()][j.parse::<usize>().unwrap()] =
                    v.parse().unwrap()
            }
            ["comp", i, j, v] => {
                r.comp[i.parse::<usize>().unwrap()][j.parse::<usize>().unwrap()] =
                    v.parse().unwrap()
            }
            ["mean", j, v] => r.mean[j.parse::<usize>().unwrap()] = v.parse().unwrap(),
            ["eigval", i, v] => r.eigval[i.parse::<usize>().unwrap()] = v.parse().unwrap(),
            ["variance", i, v] => r.variance[i.parse::<usize>().unwrap()] = v.parse().unwrap(),
            ["ind", i, v] => r.ind[i.parse::<usize>().unwrap()] = v.parse().unwrap(),
            ["unknown", j, v] => r.unknown[j.parse::<usize>().unwrap()] = v.parse().unwrap(),
            ["fit_weight", i, v] => r.fit_weight[i.parse::<usize>().unwrap()] = v.parse().unwrap(),
            ["fit_yfit", j, v] => r.fit_yfit.push((j.parse().unwrap(), v.parse().unwrap())),
            _ => {}
        }
    }
    r
}

/// max abs difference, comparing two component rows up to an overall sign:
/// pick the sign that minimizes the mismatch (align on the largest-|value| entry).
fn row_diff_upto_sign(got: &[f64], want: &[f64]) -> f64 {
    let pivot = want
        .iter()
        .enumerate()
        .max_by(|a, b| a.1.abs().partial_cmp(&b.1.abs()).unwrap())
        .map(|(i, _)| i)
        .unwrap();
    let sign = if got[pivot].signum() == want[pivot].signum() {
        1.0
    } else {
        -1.0
    };
    got.iter()
        .zip(want)
        .map(|(&g, &w)| (sign * g - w).abs())
        .fold(0.0_f64, f64::max)
}

#[test]
fn pca_train_matches_larch() {
    let r = load_ref();
    let model = pca_train(&r.ydat);

    assert_eq!(model.nsig, r.nsig, "nsig");
    assert_eq!(model.eigenvalues.len(), r.narr);

    let mut wmean = 0.0_f64;
    for j in 0..r.nfreq {
        wmean = wmean.max((model.mean[j] - r.mean[j]).abs());
    }
    assert!(wmean < 1e-12, "mean worst {wmean:.2e}");

    // eigenvalues / variances / ind are eigenvalue-derived (sign-independent).
    // Compare relative for eigenvalues (they span ~1e2..1e-15).
    let mut weig = 0.0_f64;
    for i in 0..r.narr {
        let scale = r.eigval[i].abs().max(1.0);
        weig = weig.max((model.eigenvalues[i] - r.eigval[i]).abs() / scale);
        assert!(
            (model.variances[i] - r.variance[i]).abs() < 1e-10,
            "variance[{i}] {} vs {}",
            model.variances[i],
            r.variance[i]
        );
        assert!(
            (model.ind[i] - r.ind[i]).abs() < 1e-10 + 1e-10 * r.ind[i].abs(),
            "ind[{i}] {} vs {}",
            model.ind[i],
            r.ind[i]
        );
    }
    assert!(weig < 1e-9, "eigenvalue rel worst {weig:.2e}");

    // components up to per-row sign
    let mut wcomp = 0.0_f64;
    for i in 0..r.narr {
        let d = row_diff_upto_sign(&model.components[i], &r.comp[i]);
        wcomp = wcomp.max(d);
        assert!(d < 1e-8, "component[{i}] up-to-sign diff {d:.2e}");
    }
    eprintln!("pca_train worst: mean={wmean:.2e} eig_rel={weig:.2e} comp={wcomp:.2e}");
}

#[test]
fn pca_fit_matches_larch() {
    let r = load_ref();
    let model = pca_train(&r.ydat);
    let fit = pca_fit(&r.unknown, &model, r.ncomps, true);

    let scale = r.scalars["fit_scale"];
    let chisq = r.scalars["fit_chisq"];
    assert!(
        (fit.data_scale - scale).abs() < 1e-9,
        "scale {} vs {scale}",
        fit.data_scale
    );
    assert!(
        (fit.chi_square - chisq).abs() < 1e-9 + 1e-9 * chisq.abs(),
        "chisq {} vs {chisq}",
        fit.chi_square
    );

    // weights track component signs; the larch reference fixes a sign per
    // component, so compare against the reference component sign per index.
    // yfit (the actual reconstruction) is sign-independent and the strict check.
    let mut wy = 0.0_f64;
    for &(j, want) in &r.fit_yfit {
        wy = wy.max((fit.yfit[j] - want).abs());
        assert!(
            (fit.yfit[j] - want).abs() < 1e-9,
            "yfit[{j}] {} vs {want}",
            fit.yfit[j]
        );
    }
    eprintln!(
        "pca_fit worst: yfit={wy:.2e} scale_d={:.2e} chisq_d={:.2e}",
        (fit.data_scale - scale).abs(),
        (fit.chi_square - chisq).abs()
    );
}
