//! `lincombo_fit` (XANES LCF) vs `larch` on synthetic Cu-derived standards.
//!
//! Reference generated by `scripts/ref_lincombo.py`. The synthetic component
//! and target arrays are fed identically into the Rust port. Parity is not
//! bit-exact: the lstsq seed uses nalgebra's SVD (vs LAPACK `gelsd`), so the
//! seed agrees to ~1e-11 and the refined weights to ~1e-9.

use std::collections::HashMap;
use std::path::PathBuf;

use feffit::xasproc::{LincomboParams, lincombo_fit};

fn data(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/data")
        .join(name)
}

struct Ref {
    npts: usize,
    ncomps: usize,
    cols: HashMap<String, Vec<f64>>,
    scalars: HashMap<String, f64>,
    yfit: Vec<(usize, f64)>,
}

fn load_ref() -> Ref {
    let text = std::fs::read_to_string(data("ref_lincombo.txt")).unwrap();
    let mut npts = 0usize;
    let mut ncomps = 0usize;
    let mut cols: HashMap<String, Vec<f64>> = HashMap::new();
    let mut scalars = HashMap::new();
    let mut yfit = Vec::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let parts: Vec<&str> = s.split_whitespace().collect();
        match parts.as_slice() {
            [key, val] => match *key {
                "npts" => npts = val.parse().unwrap(),
                "ncomps" => ncomps = val.parse().unwrap(),
                _ => {
                    scalars.insert(key.to_string(), val.parse().unwrap());
                }
            },
            [key, i, val] => {
                let i: usize = i.parse().unwrap();
                let v: f64 = val.parse().unwrap();
                match *key {
                    "yfit" => yfit.push((i, v)),
                    "ydat" | "comp0" | "comp1" | "comp2" => {
                        let col = cols.entry(key.to_string()).or_default();
                        if col.len() <= i {
                            col.resize(i + 1, 0.0);
                        }
                        col[i] = v;
                    }
                    _ => panic!("unexpected array {key}"),
                }
            }
            _ => panic!("bad line: {s}"),
        }
    }
    Ref {
        npts,
        ncomps,
        cols,
        scalars,
        yfit,
    }
}

#[test]
fn lincombo_matches_larch() {
    let r = load_ref();
    let ydat = &r.cols["ydat"];
    let ycomps: Vec<Vec<f64>> = (0..r.ncomps)
        .map(|i| r.cols[&format!("comp{i}")].clone())
        .collect();
    assert_eq!(ydat.len(), r.npts);

    let out = lincombo_fit(ydat, &ycomps, &LincomboParams::default());

    // refined weights: ~1e-9 (lmfit ftol/xtol = 1.5e-8)
    let mut wworst = 0.0_f64;
    for i in 0..r.ncomps {
        let want = r.scalars[&format!("w{i}")];
        let d = (out.weights[i] - want).abs();
        wworst = wworst.max(d);
        assert!(d < 1e-9, "w{i} {} vs {want} (abs {d})", out.weights[i]);
    }
    // lstsq seed: ~1e-11 (nalgebra SVD vs LAPACK gelsd)
    let mut lworst = 0.0_f64;
    for i in 0..r.ncomps {
        let want = r.scalars[&format!("ls{i}")];
        let d = (out.weights_lstsq[i] - want).abs();
        lworst = lworst.max(d);
        assert!(
            d < 1e-10,
            "ls{i} {} vs {want} (abs {d})",
            out.weights_lstsq[i]
        );
    }

    let chk = |name: &str, got: f64, tol: f64| {
        let want = r.scalars[name];
        let d = (got - want).abs();
        assert!(
            d < tol + tol * want.abs(),
            "{name} {got} vs {want} (abs {d})"
        );
    };
    chk("chisqr", out.chisqr, 1e-9);
    chk("redchi", out.redchi, 1e-9);
    chk("rfactor", out.rfactor, 1e-9);
    assert!((out.total - 1.0).abs() < 1e-12, "total {} != 1", out.total);

    let mut yworst = 0.0_f64;
    for &(i, w) in &r.yfit {
        let d = (out.yfit[i] - w).abs();
        yworst = yworst.max(d);
        assert!(d < 1e-9, "yfit[{i}] {} vs {w} (abs {d})", out.yfit[i]);
    }
    eprintln!("lincombo worst: weights={wworst:.2e} lstsq={lworst:.2e} yfit={yworst:.2e}");
}
