//! `feffit::xasproc::clean` deglitch index resolution vs `larch`
//! `larch.math.utils.{index_of, index_nearest}` (which back larch's interactive
//! deglitch in `wxxas/datatasks.py`).
//!
//! Reference generated by `scripts/ref_clean.py`. The deglitch masks resolve
//! their cut points through these two larch primitives, so this checks (a) the
//! resolvers match larch on a probe set spanning below-min / exact / between /
//! tie / above-max, and (b) the point/range masks drop exactly the
//! larch-resolved indices. Trim is a pure inclusive-window comparison with no
//! larch counterpart and is covered by unit tests.

use std::path::PathBuf;

use feffit::xasproc::RangeSide;
use feffit::xasproc::mathutils::{index_nearest, index_of};

fn load() -> std::collections::HashMap<String, Vec<f64>> {
    let path: PathBuf = [env!("CARGO_MANIFEST_DIR"), "tests", "data", "ref_clean.txt"]
        .iter()
        .collect();
    let text = std::fs::read_to_string(path).expect("read ref_clean.txt");
    let mut m = std::collections::HashMap::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut it = line.split_whitespace();
        let key = it.next().unwrap().to_owned();
        m.insert(key, it.map(|t| t.parse::<f64>().unwrap()).collect());
    }
    m
}

#[test]
fn index_resolvers_match_larch() {
    let r = load();
    let grid = &r["grid"];
    let probes = &r["probes"];
    for (k, &p) in probes.iter().enumerate() {
        let want_of = r["index_of"][k] as usize;
        let want_nr = r["index_nearest"][k] as usize;
        assert_eq!(index_of(grid, p), want_of, "index_of(probe {p})");
        assert_eq!(index_nearest(grid, p), want_nr, "index_nearest(probe {p})");
    }
}

#[test]
fn deglitch_masks_drop_larch_resolved_indices() {
    let r = load();
    let grid = &r["grid"];
    let n = grid.len();
    let probes = &r["probes"];
    let nearest = &r["index_nearest"];

    // Point removal drops exactly index_nearest(probe).
    for (k, &p) in probes.iter().enumerate() {
        let i1 = nearest[k] as usize;
        let mask = feffit::xasproc::deglitch_point_mask(grid, p);
        for (i, &keep) in mask.iter().enumerate() {
            assert_eq!(keep, i != i1, "point@{p}: index {i}");
        }
    }

    // Range removal: pick an interior probe (7100 -> i1=40). Above drops [i1, end);
    // Below drops [0, i1). i1 itself is kept by Below, dropped by Above.
    let k = probes
        .iter()
        .position(|&p| p == 7100.0)
        .expect("7100 probe");
    let i1 = nearest[k] as usize;
    let above = feffit::xasproc::deglitch_range_mask(grid, RangeSide::Above, 7100.0, 0.0);
    let below = feffit::xasproc::deglitch_range_mask(grid, RangeSide::Below, 7100.0, 0.0);
    for i in 0..n {
        assert_eq!(above[i], i < i1, "above@7100 index {i}");
        assert_eq!(below[i], i >= i1, "below@7100 index {i}");
    }

    // Between two probes drops the half-open span [lo, hi) of their nearest indices.
    let (ka, kb) = (
        probes.iter().position(|&p| p == 7100.0).unwrap(),
        probes.iter().position(|&p| p == 7123.75).unwrap(),
    );
    let (ia, ib) = (nearest[ka] as usize, nearest[kb] as usize);
    let (lo, hi) = (ia.min(ib), ia.max(ib));
    let between = feffit::xasproc::deglitch_range_mask(grid, RangeSide::Between, 7100.0, 7123.75);
    for (i, &keep) in between.iter().enumerate() {
        assert_eq!(keep, !(lo..hi).contains(&i), "between index {i}");
    }
}
