//! AUTOBK uncertainty bands (`autobk_delta_chi`) vs `larch`.
//!
//! Reference generated by `scripts/ref_autobk_delta.py` on the Cu foil `mu(E)`
//! with `calc_uncertainties=True, err_sigma=1`. Covers the covariance the bands
//! derive from (`covar`, `coefs_std`, `redchi`), the scalar intermediates
//! (`prob`, the two Student-t percent points), and the sampled `delta_chi` /
//! `delta_bkg` arrays.

use std::collections::HashMap;
use std::path::PathBuf;

use xasproc::special::{erf, t_ppf};
use xasproc::{AutobkParams, autobk, autobk_delta_chi};

fn data(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/data")
        .join(name)
}

fn load_xmu() -> (Vec<f64>, Vec<f64>) {
    let text = std::fs::read_to_string(data("cu.xmu")).unwrap();
    let mut e = Vec::new();
    let mut m = Vec::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        e.push(it.next().unwrap().parse().unwrap());
        m.push(it.next().unwrap().parse().unwrap());
    }
    (e, m)
}

struct Ref {
    scalars: HashMap<String, f64>,
    // covar[(i,j)], coefs_std[i], dchi[i], dbkg[i]
    covar: HashMap<(usize, usize), f64>,
    coefs_std: HashMap<usize, f64>,
    dchi: Vec<(usize, f64)>,
    dbkg: Vec<(usize, f64)>,
}

fn load_ref() -> Ref {
    let text = std::fs::read_to_string(data("ref_autobk_delta.txt")).unwrap();
    let mut scalars = HashMap::new();
    let mut covar = HashMap::new();
    let mut coefs_std = HashMap::new();
    let mut dchi = Vec::new();
    let mut dbkg = Vec::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        let key = it.next().unwrap();
        match key {
            "covar" => {
                let i: usize = it.next().unwrap().parse().unwrap();
                let j: usize = it.next().unwrap().parse().unwrap();
                let v: f64 = it.next().unwrap().parse().unwrap();
                covar.insert((i, j), v);
            }
            "coefs_std" => {
                let i: usize = it.next().unwrap().parse().unwrap();
                let v: f64 = it.next().unwrap().parse().unwrap();
                coefs_std.insert(i, v);
            }
            "dchi" => {
                let i: usize = it.next().unwrap().parse().unwrap();
                let v: f64 = it.next().unwrap().parse().unwrap();
                dchi.push((i, v));
            }
            "dbkg" => {
                let i: usize = it.next().unwrap().parse().unwrap();
                let v: f64 = it.next().unwrap().parse().unwrap();
                dbkg.push((i, v));
            }
            // skip the sf_erf / sf_tppf spot tables (covered by special.rs units)
            "sf_erf" | "sf_tppf" => {}
            _ => {
                scalars.insert(key.to_string(), it.next().unwrap().parse().unwrap());
            }
        }
    }
    Ref {
        scalars,
        covar,
        coefs_std,
        dchi,
        dbkg,
    }
}

fn rel(g: f64, w: f64) -> f64 {
    (g - w).abs() / w.abs().max(1e-300)
}

#[test]
fn autobk_delta_chi_matches_larch() {
    let (energy, mu) = load_xmu();
    let r = load_ref();
    let ab = autobk(&energy, &mu, &AutobkParams::default());
    let delta = autobk_delta_chi(&ab, 1.0).expect("delta should be computed");

    // structural integers (exact)
    let nspl = ab.nspl;
    assert_eq!(nspl as f64, r.scalars["nspl"], "nspl");
    assert_eq!(ab.iek0 as f64, r.scalars["iek0"], "iek0");
    assert_eq!(ab.iemax as f64, r.scalars["iemax"], "iemax");
    assert_eq!(ab.k.len() as f64, r.scalars["nchi"], "nchi");
    let nmue = ab.iemax - ab.iek0 + 1;
    assert_eq!(nmue as f64, r.scalars["nmue"], "nmue");
    assert_eq!(delta.delta_chi.len() as f64, r.scalars["ndchi"], "ndchi");
    assert_eq!(delta.delta_bkg.len() as f64, r.scalars["ndbkg"], "ndbkg");

    // fit statistics
    assert!(
        rel(ab.chisqr, r.scalars["chisqr"]) < 1e-9,
        "chisqr {} vs {} rel {}",
        ab.chisqr,
        r.scalars["chisqr"],
        rel(ab.chisqr, r.scalars["chisqr"])
    );
    assert!(
        rel(ab.redchi, r.scalars["redchi"]) < 1e-9,
        "redchi {} vs {} rel {}",
        ab.redchi,
        r.scalars["redchi"],
        rel(ab.redchi, r.scalars["redchi"])
    );

    // scalar intermediates: prob (erf) and the two Student-t percent points
    let prob = 0.5 * (1.0 + erf(1.0 / 2.0_f64.sqrt()));
    assert!(rel(prob, r.scalars["prob"]) < 1e-13, "prob {prob}");
    let df_chi = (ab.k.len() - nspl) as f64;
    let df_bkg = (nmue - nspl) as f64;
    let tppf_chi = t_ppf(prob, df_chi);
    let tppf_bkg = t_ppf(prob, df_bkg);
    assert!(
        rel(tppf_chi, r.scalars["tppf_chi"]) < 1e-12,
        "tppf_chi {} vs {} rel {}",
        tppf_chi,
        r.scalars["tppf_chi"],
        rel(tppf_chi, r.scalars["tppf_chi"])
    );
    assert!(
        rel(tppf_bkg, r.scalars["tppf_bkg"]) < 1e-12,
        "tppf_bkg {} vs {} rel {}",
        tppf_bkg,
        r.scalars["tppf_bkg"],
        rel(tppf_bkg, r.scalars["tppf_bkg"])
    );

    // covariance and per-coefficient std (the fit covariance feeding the bands)
    let covar = ab.covar.as_ref().expect("covar");
    let mut w_covar = 0.0_f64;
    for (&(i, j), &want) in &r.covar {
        let got = covar[i][j];
        w_covar = w_covar.max(rel(got, want));
        assert!(
            rel(got, want) < 1e-10,
            "covar[{i},{j}] {got} vs {want} rel {}",
            rel(got, want)
        );
    }
    let mut w_std = 0.0_f64;
    for (&i, &want) in &r.coefs_std {
        let got = ab.coefs_std[i];
        w_std = w_std.max(rel(got, want));
        assert!(
            rel(got, want) < 1e-10,
            "coefs_std[{i}] {got} vs {want} rel {}",
            rel(got, want)
        );
    }

    // the uncertainty bands themselves
    let mut w_dchi = 0.0_f64;
    for &(i, want) in &r.dchi {
        let got = delta.delta_chi[i];
        w_dchi = w_dchi.max(rel(got, want));
        assert!(
            rel(got, want) < 1e-10,
            "delta_chi[{i}] {got} vs {want} rel {}",
            rel(got, want)
        );
    }
    let mut w_dbkg = 0.0_f64;
    for &(i, want) in &r.dbkg {
        let got = delta.delta_bkg[i];
        // delta_bkg is mostly zero outside the fit window; compare absolutely
        // there and relatively where nonzero.
        let d = if want.abs() < 1e-300 {
            got.abs()
        } else {
            rel(got, want)
        };
        w_dbkg = w_dbkg.max(d);
        assert!(d < 1e-10, "delta_bkg[{i}] {got} vs {want} (metric {d})");
    }

    eprintln!(
        "worst rel: covar={w_covar:.2e} coefs_std={w_std:.2e} \
         dchi={w_dchi:.2e} dbkg={w_dbkg:.2e}; tppf_chi rel={:.2e} tppf_bkg rel={:.2e}",
        rel(tppf_chi, r.scalars["tppf_chi"]),
        rel(tppf_bkg, r.scalars["tppf_bkg"]),
    );
}
