//! AUTOBK background removal vs `larch`.
//!
//! Reference generated by `scripts/ref_autobk.py` on the Cu foil `mu(E)`.

use std::collections::HashMap;
use std::path::PathBuf;

use xasproc::{AutobkParams, autobk};

fn data(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/data")
        .join(name)
}

fn load_xmu() -> (Vec<f64>, Vec<f64>) {
    let text = std::fs::read_to_string(data("cu.xmu")).unwrap();
    let mut e = Vec::new();
    let mut m = Vec::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        e.push(it.next().unwrap().parse().unwrap());
        m.push(it.next().unwrap().parse().unwrap());
    }
    (e, m)
}

struct Ref {
    scalars: HashMap<String, f64>,
    arrays: HashMap<String, Vec<(usize, f64)>>,
}

fn load_ref() -> Ref {
    let text = std::fs::read_to_string(data("ref_autobk.txt")).unwrap();
    let mut scalars = HashMap::new();
    let mut arrays: HashMap<String, Vec<(usize, f64)>> = HashMap::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        let key = it.next().unwrap();
        match key {
            "k" | "chi" | "bkg" | "chie" | "initbkg" | "initchi" => {
                let i: usize = it.next().unwrap().parse().unwrap();
                let v: f64 = it.next().unwrap().parse().unwrap();
                arrays.entry(key.to_string()).or_default().push((i, v));
            }
            _ => {
                scalars.insert(key.to_string(), it.next().unwrap().parse().unwrap());
            }
        }
    }
    Ref { scalars, arrays }
}

fn rel(g: f64, w: f64) -> f64 {
    (g - w).abs() / w.abs().max(1e-300)
}

#[test]
fn autobk_matches_larch() {
    let (energy, mu) = load_xmu();
    let r = load_ref();
    let ab = autobk(&energy, &mu, &AutobkParams::default());

    // integer / structural scalars (exact)
    assert_eq!(ab.ek0, r.scalars["ek0"], "ek0");
    assert_eq!(ab.nspl as f64, r.scalars["nspl"], "nspl");
    assert_eq!(ab.irbkg as f64, r.scalars["irbkg"], "irbkg");
    assert_eq!(ab.iek0 as f64, r.scalars["iek0"], "iek0");
    assert_eq!(ab.iemax as f64, r.scalars["iemax"], "iemax");
    assert_eq!(ab.k.len() as f64, r.scalars["nk"], "nk");
    assert_eq!(ab.bkg.len() as f64, r.scalars["nbkg"], "nbkg");
    assert_eq!(ab.rbkg, r.scalars["rbkg"], "rbkg");
    assert!(
        rel(ab.edge_step, r.scalars["edge_step"]) < 1e-10,
        "edge_step {} vs {}",
        ab.edge_step,
        r.scalars["edge_step"]
    );
    assert!(
        rel(ab.kmax, r.scalars["kmax"]) < 1e-12,
        "kmax {} vs {}",
        ab.kmax,
        r.scalars["kmax"]
    );

    // k grid is exact (kstep * arange)
    let kcheck = |name: &str, arr: &[f64], tol: f64| -> f64 {
        let mut worst = 0.0_f64;
        for &(i, want) in &r.arrays[name] {
            let got = arr[i];
            let d = (got - want).abs();
            worst = worst.max(d);
            assert!(
                d < 1e-12 + tol * want.abs().max(1.0),
                "{name}[{i}] {got} vs {want} (abs {d})"
            );
        }
        worst
    };
    kcheck("k", &ab.k, 1e-12);

    // deterministic pre-fit spline (depends only on FITPACK splrep/splev):
    // rusty-fitpack reproduces scipy FITPACK to machine precision.
    let w_initbkg = kcheck("initbkg", &ab.init_bkg, 1e-12);
    let w_initchi = kcheck("initchi", &ab.init_chi, 1e-12);

    // fit-dependent outputs (FITPACK port + MINPACK lmdif): lm::lmdif matches
    // scipy.leastsq, so these land near machine precision too (worst ~1e-14).
    let w_bkg = kcheck("bkg", &ab.bkg, 1e-11);
    let w_chi = kcheck("chi", &ab.chi, 1e-11);
    let w_chie = kcheck("chie", &ab.chie, 1e-11);

    eprintln!(
        "worst abs deltas: initbkg={w_initbkg:.2e} initchi={w_initchi:.2e} \
         bkg={w_bkg:.2e} chi={w_chi:.2e} chie={w_chie:.2e}"
    );
}
