//! `xas_deconvolve` / `xas_convolve` vs `larch`.
//!
//! Reference generated by `scripts/ref_deconvolve.py` on the Cu foil `mu(E)`
//! (pre_edge-normalized).

use std::collections::HashMap;
use std::path::PathBuf;

use xasproc::{
    pre_edge, xas_convolve, xas_deconvolve, ConvParams, DeconvForm, DeconvParams, PreEdgeParams,
};

fn data(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/data")
        .join(name)
}

fn load_xmu() -> (Vec<f64>, Vec<f64>) {
    let text = std::fs::read_to_string(data("cu.xmu")).unwrap();
    let mut e = Vec::new();
    let mut m = Vec::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        e.push(it.next().unwrap().parse().unwrap());
        m.push(it.next().unwrap().parse().unwrap());
    }
    (e, m)
}

fn load_ref() -> HashMap<String, Vec<(usize, f64)>> {
    let text = std::fs::read_to_string(data("ref_deconvolve.txt")).unwrap();
    let mut arrays: HashMap<String, Vec<(usize, f64)>> = HashMap::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        let key = it.next().unwrap();
        if key.ends_with("_n") || key == "npts" {
            continue;
        }
        let i: usize = it.next().unwrap().parse().unwrap();
        let v: f64 = it.next().unwrap().parse().unwrap();
        arrays.entry(key.to_string()).or_default().push((i, v));
    }
    arrays
}

fn check(name: &str, got: &[f64], want: &[(usize, f64)], tol: f64) -> f64 {
    let mut worst = 0.0_f64;
    for &(i, w) in want {
        let g = got[i];
        let d = (g - w).abs();
        worst = worst.max(d);
        assert!(d < tol + tol * w.abs(), "{name}[{i}] {g} vs {w} (abs {d})");
    }
    worst
}

#[test]
fn deconvolve_matches_larch() {
    let (energy, mu) = load_xmu();
    let pe = pre_edge(&energy, &mu, &PreEdgeParams::defaults());
    let r = load_ref();

    // deconvolve uses pre_edge's normalized mu on the cleaned energy grid
    let en = &pe.energy;
    let norm = &pe.norm;

    let mut p = DeconvParams::default();
    let w1 = check(
        "dec_lor_smooth",
        &xas_deconvolve(en, norm, &p),
        &r["dec_lor_smooth"],
        1e-11,
    );
    p.smooth = false;
    let w2 = check(
        "dec_lor_raw",
        &xas_deconvolve(en, norm, &p),
        &r["dec_lor_raw"],
        1e-11,
    );
    let pg = DeconvParams {
        form: DeconvForm::Gaussian,
        ..Default::default()
    };
    let w3 = check(
        "dec_gau_smooth",
        &xas_deconvolve(en, norm, &pg),
        &r["dec_gau_smooth"],
        1e-11,
    );

    let cl = ConvParams::default();
    let w4 = check(
        "con_lor",
        &xas_convolve(en, norm, &cl),
        &r["con_lor"],
        1e-11,
    );
    let cg = ConvParams {
        form: DeconvForm::Gaussian,
        ..Default::default()
    };
    let w5 = check(
        "con_gau",
        &xas_convolve(en, norm, &cg),
        &r["con_gau"],
        1e-11,
    );

    eprintln!(
        "worst abs deltas: dec_lor={w1:.2e} dec_raw={w2:.2e} dec_gau={w3:.2e} \
         con_lor={w4:.2e} con_gau={w5:.2e}"
    );
}
