//! `mback` / `mback_norm` vs `larch` (z=29, Cu K edge).
//!
//! Reference generated by `scripts/ref_mback.py`. The Chantler `f2`/`f1` larch
//! computes internally (via `xraydb`) are dumped at full resolution and fed
//! *identically* into the Rust port, isolating the MBACK algorithm from the
//! atomic-data table source so the comparison is bit-exact.

use std::collections::HashMap;
use std::path::PathBuf;

use xasproc::{MbackNormParams, MbackParams, mback, mback_norm};

fn data(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/data")
        .join(name)
}

fn load_xmu() -> (Vec<f64>, Vec<f64>) {
    let text = std::fs::read_to_string(data("cu.xmu")).unwrap();
    let mut e = Vec::new();
    let mut m = Vec::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        e.push(it.next().unwrap().parse().unwrap());
        m.push(it.next().unwrap().parse().unwrap());
    }
    (e, m)
}

struct Ref {
    f1: Vec<f64>,
    f2: Vec<f64>,
    scalars: HashMap<String, f64>,
    arrays: HashMap<String, Vec<(usize, f64)>>,
}

fn load_ref(npts: usize) -> Ref {
    let text = std::fs::read_to_string(data("ref_mback.txt")).unwrap();
    let mut f1 = vec![0.0; npts];
    let mut f2 = vec![0.0; npts];
    let mut scalars = HashMap::new();
    let mut arrays: HashMap<String, Vec<(usize, f64)>> = HashMap::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let parts: Vec<&str> = s.split_whitespace().collect();
        match parts.as_slice() {
            [key, val] => {
                if *key != "npts" {
                    scalars.insert(key.to_string(), val.parse().unwrap());
                }
            }
            [key, i, val] => {
                let i: usize = i.parse().unwrap();
                let v: f64 = val.parse().unwrap();
                match *key {
                    "f1" => f1[i] = v,
                    "f2" => f2[i] = v,
                    _ => arrays.entry(key.to_string()).or_default().push((i, v)),
                }
            }
            _ => panic!("bad line: {s}"),
        }
    }
    Ref {
        f1,
        f2,
        scalars,
        arrays,
    }
}

fn check_arr(name: &str, got: &[f64], want: &[(usize, f64)], tol: f64) -> f64 {
    let mut worst = 0.0_f64;
    for &(i, w) in want {
        let g = got[i];
        let d = (g - w).abs();
        worst = worst.max(d);
        assert!(d < tol + tol * w.abs(), "{name}[{i}] {g} vs {w} (abs {d})");
    }
    worst
}

fn check_scalar(name: &str, got: f64, want: f64, tol: f64) -> f64 {
    let d = (got - want).abs();
    assert!(
        d < tol + tol * want.abs(),
        "{name} {got} vs {want} (abs {d})"
    );
    d
}

#[test]
fn mback_matches_larch() {
    let (energy, mu) = load_xmu();
    let r = load_ref(energy.len());

    let mb = mback(&energy, &mu, &r.f2, Some(&r.f1), &MbackParams::default());

    let mut w = 0.0_f64;
    w = w.max(check_scalar("mb_e0", mb.e0, r.scalars["mb_e0"], 1e-12));
    w = w.max(check_scalar(
        "mb_edge_step",
        mb.edge_step,
        r.scalars["mb_edge_step"],
        1e-11,
    ));
    w = w.max(check_scalar("mb_s", mb.s, r.scalars["mb_s"], 1e-11));
    for i in 0..4 {
        w = w.max(check_scalar(
            &format!("mb_c{i}"),
            mb.coefs[i],
            r.scalars[&format!("mb_c{i}")],
            1e-11,
        ));
    }
    w = w.max(check_arr("mb_fpp", &mb.fpp, &r.arrays["mb_fpp"], 1e-10));
    w = w.max(check_arr("mb_norm", &mb.norm, &r.arrays["mb_norm"], 1e-10));
    w = w.max(check_arr(
        "mb_normfunc",
        &mb.norm_function,
        &r.arrays["mb_normfunc"],
        1e-10,
    ));
    eprintln!("mback worst abs delta: {w:.2e}");
}

#[test]
fn mback_norm_matches_larch() {
    let (energy, mu) = load_xmu();
    let r = load_ref(energy.len());

    let mn = mback_norm(&energy, &mu, &r.f2, &MbackNormParams::defaults());

    let mut w = 0.0_f64;
    w = w.max(check_scalar(
        "mn_edge_step",
        mn.edge_step,
        r.scalars["mn_edge_step"],
        1e-11,
    ));
    w = w.max(check_scalar(
        "mn_edge_step_poly",
        mn.edge_step_poly,
        r.scalars["mn_edge_step_poly"],
        1e-11,
    ));
    w = w.max(check_scalar(
        "mn_slope",
        mn.slope,
        r.scalars["mn_slope"],
        1e-11,
    ));
    w = w.max(check_scalar(
        "mn_offset",
        mn.offset,
        r.scalars["mn_offset"],
        1e-11,
    ));
    w = w.max(check_scalar(
        "mn_scale",
        mn.scale,
        r.scalars["mn_scale"],
        1e-11,
    ));
    w = w.max(check_arr("mn_norm", &mn.norm, &r.arrays["mn_norm"], 1e-10));
    w = w.max(check_arr(
        "mn_mback_mu",
        &mn.mback_mu,
        &r.arrays["mn_mback_mu"],
        1e-10,
    ));
    w = w.max(check_arr(
        "mn_model",
        &mn.model,
        &r.arrays["mn_model"],
        1e-10,
    ));
    w = w.max(check_arr(
        "mn_weights",
        &mn.weights,
        &r.arrays["mn_weights"],
        1e-12,
    ));
    eprintln!("mback_norm worst abs delta: {w:.2e}");
}
