//! `pre_edge` (pre-edge subtraction + normalization) vs `larch`.
//!
//! Reference generated by `scripts/ref_preedge.py` on the Cu foil `mu(E)`.

use std::collections::HashMap;
use std::path::PathBuf;

use xasproc::{pre_edge, PreEdgeParams};

fn data(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/data")
        .join(name)
}

fn load_xmu() -> (Vec<f64>, Vec<f64>) {
    let text = std::fs::read_to_string(data("cu.xmu")).unwrap();
    let mut e = Vec::new();
    let mut m = Vec::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        e.push(it.next().unwrap().parse().unwrap());
        m.push(it.next().unwrap().parse().unwrap());
    }
    (e, m)
}

struct Ref {
    scalars: HashMap<String, f64>,
    arrays: HashMap<String, Vec<(usize, f64)>>,
}

fn load_ref() -> Ref {
    let text = std::fs::read_to_string(data("ref_preedge.txt")).unwrap();
    let mut scalars = HashMap::new();
    let mut arrays: HashMap<String, Vec<(usize, f64)>> = HashMap::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        let key = it.next().unwrap();
        match key {
            "norm" | "flat" | "preedge" | "postedge" | "dmude" => {
                let i: usize = it.next().unwrap().parse().unwrap();
                let v: f64 = it.next().unwrap().parse().unwrap();
                arrays.entry(key.to_string()).or_default().push((i, v));
            }
            _ => {
                scalars.insert(key.to_string(), it.next().unwrap().parse().unwrap());
            }
        }
    }
    Ref { scalars, arrays }
}

fn rel(g: f64, w: f64) -> f64 {
    (g - w).abs() / w.abs().max(1e-300)
}

#[test]
fn pre_edge_matches_larch() {
    let (energy, mu) = load_xmu();
    let r = load_ref();
    let pe = pre_edge(&energy, &mu, &PreEdgeParams::defaults());

    // scalars
    assert_eq!(pe.e0, r.scalars["e0"], "e0");
    assert!(
        rel(pe.edge_step, r.scalars["edge_step"]) < 1e-10,
        "edge_step {} vs {}",
        pe.edge_step,
        r.scalars["edge_step"]
    );
    assert_eq!(pe.pre1, r.scalars["pre1"], "pre1");
    assert_eq!(pe.pre2, r.scalars["pre2"], "pre2");
    assert_eq!(pe.norm1, r.scalars["norm1"], "norm1");
    assert!(rel(pe.norm2, r.scalars["norm2"]) < 1e-12, "norm2");
    assert_eq!(pe.nnorm, r.scalars["nnorm"] as usize, "nnorm");
    assert_eq!(pe.nvict, r.scalars["nvict"] as i32, "nvict");
    assert!(
        rel(pe.precoefs[0], r.scalars["pre_offset"]) < 1e-9,
        "pre_offset {} vs {}",
        pe.precoefs[0],
        r.scalars["pre_offset"]
    );
    assert!(
        rel(pe.precoefs[1], r.scalars["pre_slope"]) < 1e-9,
        "pre_slope {} vs {}",
        pe.precoefs[1],
        r.scalars["pre_slope"]
    );

    // arrays
    let check = |name: &str, arr: &[f64], tol: f64| {
        for &(i, want) in &r.arrays[name] {
            let got = arr[i];
            assert!(
                (got - want).abs() < 1e-9 + tol * want.abs(),
                "{name}[{i}] {got} vs {want}"
            );
        }
    };
    check("norm", &pe.norm, 1e-9);
    check("flat", &pe.flat, 1e-9);
    check("preedge", &pe.pre_edge, 1e-9);
    check("postedge", &pe.post_edge, 1e-9);
    check("dmude", &pe.dmude, 1e-8);
}
