//! `rebin_xafs` / `sort_xafs` vs `larch`.
//!
//! Reference generated by `scripts/ref_rebin.py` on the Cu foil `mu(E)`.

use std::collections::HashMap;
use std::path::PathBuf;

use xasproc::{RebinMethod, RebinParams, rebin_xafs, sort_xafs};

fn data(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/data")
        .join(name)
}

fn load_xmu() -> (Vec<f64>, Vec<f64>) {
    let text = std::fs::read_to_string(data("cu.xmu")).unwrap();
    let mut e = Vec::new();
    let mut m = Vec::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        e.push(it.next().unwrap().parse().unwrap());
        m.push(it.next().unwrap().parse().unwrap());
    }
    (e, m)
}

struct Rows {
    scalars: HashMap<String, f64>,
    // method -> Vec<(energy, mu, delta_mu)>
    rows: HashMap<String, Vec<(f64, f64, f64)>>,
}

fn load_ref() -> Rows {
    let text = std::fs::read_to_string(data("ref_rebin.txt")).unwrap();
    let mut scalars = HashMap::new();
    let mut rows: HashMap<String, Vec<(f64, f64, f64)>> = HashMap::new();
    for line in text.lines() {
        let s = line.trim();
        if s.is_empty() || s.starts_with('#') {
            continue;
        }
        let mut it = s.split_whitespace();
        let key = it.next().unwrap();
        match key {
            "boxcar" | "centroid" | "spline" => {
                let _i: usize = it.next().unwrap().parse().unwrap();
                let e: f64 = it.next().unwrap().parse().unwrap();
                let m: f64 = it.next().unwrap().parse().unwrap();
                let d: f64 = it.next().unwrap().parse().unwrap();
                rows.entry(key.to_string()).or_default().push((e, m, d));
            }
            _ => {
                scalars.insert(key.to_string(), it.next().unwrap().parse().unwrap());
            }
        }
    }
    Rows { scalars, rows }
}

fn close(a: f64, b: f64, tol: f64) -> bool {
    if a.is_nan() || b.is_nan() {
        return a.is_nan() && b.is_nan();
    }
    (a - b).abs() <= tol + tol * b.abs()
}

#[test]
fn rebin_matches_larch() {
    let (energy, mu) = load_xmu();
    let r = load_ref();
    let e0 = r.scalars["e0"];

    // boxcar/centroid are bit-exact; the spline method routes through a Thomas
    // solve in place of scipy's LAPACK solve_banded but, for these
    // well-conditioned interpolation systems, still agrees to round-off.
    for (method_name, method, mu_tol) in [
        ("boxcar", RebinMethod::Boxcar, 1e-12_f64),
        ("centroid", RebinMethod::Centroid, 1e-12_f64),
        ("spline", RebinMethod::Spline, 1e-12_f64),
    ] {
        let mut p = RebinParams::new(e0);
        p.method = method;
        let rb = rebin_xafs(&energy, &mu, &p);
        let want = &r.rows[method_name];

        assert_eq!(
            rb.energy.len(),
            r.scalars[&format!("{method_name}_n")] as usize,
            "{method_name} length"
        );
        assert_eq!(rb.energy.len(), want.len(), "{method_name} row count");

        let mut worst = 0.0_f64;
        for (i, &(we, wm, wd)) in want.iter().enumerate() {
            assert!(
                close(rb.energy[i], we, 1e-12),
                "{method_name} energy[{i}] {} vs {we}",
                rb.energy[i]
            );
            assert!(
                close(rb.mu[i], wm, mu_tol),
                "{method_name} mu[{i}] {} vs {wm}",
                rb.mu[i]
            );
            // delta_mu is the segment std (no spline) -> bit-exact for all methods
            assert!(
                close(rb.delta_mu[i], wd, 1e-12),
                "{method_name} delta_mu[{i}] {} vs {wd}",
                rb.delta_mu[i]
            );
            if !rb.mu[i].is_nan() {
                worst = worst.max((rb.mu[i] - wm).abs());
            }
        }
        eprintln!("rebin {method_name} worst abs mu delta: {worst:.2e}");
    }
}

#[test]
fn sort_matches_larch() {
    let (energy, mu) = load_xmu();
    let r = load_ref();

    // shuffle however we like; sort_xafs must recover the canonical order
    let mut e_shuf: Vec<f64> = energy.iter().rev().cloned().collect();
    let mut m_shuf: Vec<f64> = mu.iter().rev().cloned().collect();
    // interleave a swap to make it a non-trivial permutation
    e_shuf.swap(0, 5);
    m_shuf.swap(0, 5);

    let (se, sm) = sort_xafs(&e_shuf, &m_shuf, true, true);

    assert_eq!(se.len(), r.scalars["sort_n"] as usize, "sorted length");
    assert!(
        close(se[0], r.scalars["sort_e0"], 1e-12),
        "sorted first energy"
    );
    assert!(
        close(*se.last().unwrap(), r.scalars["sort_elast"], 1e-12),
        "sorted last energy"
    );
    // checksums (naive vs numpy pairwise sum -> loose relative tol)
    let e_sum: f64 = se.iter().sum();
    let m_sum: f64 = sm.iter().sum();
    assert!(
        (e_sum - r.scalars["sort_e_sum"]).abs() < 1e-4,
        "sorted energy sum {e_sum} vs {}",
        r.scalars["sort_e_sum"]
    );
    assert!(
        (m_sum - r.scalars["sort_mu_sum"]).abs() < 1e-9,
        "sorted mu sum {m_sum} vs {}",
        r.scalars["sort_mu_sum"]
    );
    // energy must be strictly increasing after sort+dedup
    assert!(
        se.windows(2).all(|w| w[1] > w[0]),
        "sorted energy monotonic"
    );
}
