#!/usr/bin/env python3
"""Generate `crates/feffit/src/feffdat/mass.rs` from xraydb's `atomic_mass`.

larch builds each path-geometry atom's mass with `xraydb.atomic_mass(iz)`
(`larch/xafs/feffdat.py`). To reproduce larch's `rmass`, `sigma2_eins`, and
`sigma2_debye` values bit-for-bit, the Rust port embeds the *same* table rather
than an independent set of standard atomic weights. This script dumps xraydb's
values (Z = 1..118) into a static Rust array, keyed by Z.

Run from the repo root with the project venv (xraydb installed):
    .venv/bin/python scripts/gen_atomic_mass.py
"""
from xraydb import atomic_mass, atomic_symbol

ZMAX = 118


def main():
    rows = []
    for z in range(1, ZMAX + 1):
        m = float(atomic_mass(z))
        sym = atomic_symbol(z)
        rows.append((z, sym, m))

    lines = []
    lines.append("//! Atomic masses (amu) by atomic number, generated by")
    lines.append("//! `scripts/gen_atomic_mass.py` from xraydb's `atomic_mass`.")
    lines.append("//!")
    lines.append("//! larch builds each path atom's mass with `xraydb.atomic_mass(iz)`")
    lines.append("//! (`larch/xafs/feffdat.py`); embedding the same table makes `rmass`,")
    lines.append("//! `sigma2_eins`, and `sigma2_debye` reproduce larch bit-for-bit. Do not")
    lines.append("//! edit by hand — regenerate with the script.")
    lines.append("")
    lines.append(f"/// Atomic masses in amu, indexed by `Z - 1` (`Z` = 1..={ZMAX}).")
    lines.append(f"pub(crate) const ATOMIC_MASS: [f64; {ZMAX}] = [")
    for z, sym, m in rows:
        lines.append(f"    {m!r}, // {z:>3} {sym}")
    lines.append("];")
    lines.append("")
    lines.append("/// Atomic mass (amu) for atomic number `iz`, or `None` if out of range.")
    lines.append("pub fn atomic_mass(iz: i64) -> Option<f64> {")
    lines.append("    if iz >= 1 && iz as usize <= ATOMIC_MASS.len() {")
    lines.append("        Some(ATOMIC_MASS[(iz - 1) as usize])")
    lines.append("    } else {")
    lines.append("        None")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    with open("crates/feffit/src/feffdat/mass.rs", "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote crates/feffit/src/feffdat/mass.rs ({ZMAX} elements)")


if __name__ == "__main__":
    main()
