//! Parity tests for `xafsft` against larch's `xafsft.py`, via the labeled-block
//! references in `tests/data/` (generated by `scripts/ref_xftf.py`, which uses
//! scipy.fftpack + scipy.special.i0 — exactly what larch uses).
//!
//! Tolerances are loose enough to absorb FFT round-off (rustfft vs FFTPACK,
//! ~1e-13) but tight enough to catch any real divergence.

use std::collections::HashMap;
use std::path::PathBuf;

use num_complex::Complex64;
use xafsft::{xftf, xftr, Window};

fn data_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/data")
}

struct Ref {
    params: HashMap<String, String>,
    blocks: HashMap<String, Vec<f64>>,
}

impl Ref {
    fn load(name: &str) -> Ref {
        let text = std::fs::read_to_string(data_dir().join(name)).unwrap();
        let mut params = HashMap::new();
        let mut blocks: HashMap<String, Vec<f64>> = HashMap::new();
        let mut cur: Option<String> = None;
        for line in text.lines() {
            if let Some(rest) = line.strip_prefix("#param ") {
                let mut it = rest.split_whitespace();
                params.insert(
                    it.next().unwrap().to_string(),
                    it.next().unwrap().to_string(),
                );
            } else if let Some(name) = line.strip_prefix("#begin ") {
                cur = Some(name.to_string());
                blocks.insert(name.to_string(), Vec::new());
            } else if line == "#end" {
                cur = None;
            } else if let Some(ref name) = cur {
                blocks.get_mut(name).unwrap().push(line.parse().unwrap());
            }
        }
        Ref { params, blocks }
    }

    fn f(&self, k: &str) -> f64 {
        self.params[k].parse().unwrap()
    }
    fn i(&self, k: &str) -> i32 {
        self.params[k].parse().unwrap()
    }
    fn win(&self) -> Window {
        Window::from_name(&self.params["window"]).unwrap()
    }
    fn blk(&self, k: &str) -> &[f64] {
        &self.blocks[k]
    }
}

fn max_abs_diff(a: &[f64], b: &[f64]) -> f64 {
    assert_eq!(
        a.len(),
        b.len(),
        "length mismatch {} vs {}",
        a.len(),
        b.len()
    );
    a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0, f64::max)
}

fn check_close(label: &str, got: &[f64], want: &[f64], tol: f64) {
    let d = max_abs_diff(got, want);
    println!("{label}: max|Δ| = {d:.3e}");
    assert!(d < tol, "{label}: diff {d:.3e} exceeds {tol:.0e}");
}

fn run_xftf_case(file: &str) {
    let r = Ref::load(file);
    let k = r.blk("k");
    let chi = r.blk("chi");
    let out = xftf(
        k,
        chi,
        r.f("kmin"),
        r.f("kmax"),
        r.i("kweight"),
        r.f("dk"),
        None,
        r.win(),
        r.f("rmax_out"),
        r.f("nfft") as usize,
        Some(r.f("kstep")),
    );
    check_close(&format!("{file} kwin"), &out.kwin, r.blk("kwin"), 1e-12);
    check_close(&format!("{file} r"), &out.r, r.blk("r"), 1e-9);
    check_close(
        &format!("{file} chir_re"),
        &out.chir_re,
        r.blk("chir_re"),
        1e-9,
    );
    check_close(
        &format!("{file} chir_im"),
        &out.chir_im,
        r.blk("chir_im"),
        1e-9,
    );
}

#[test]
fn xftf_kaiser_matches_larch() {
    run_xftf_case("ref_xftf_kaiser.txt");
}

#[test]
fn xftf_hanning_matches_larch() {
    run_xftf_case("ref_xftf_hanning.txt");
}

#[test]
fn xftr_kaiser_matches_larch() {
    let r = Ref::load("ref_xftr_kaiser.txt");
    let rr = r.blk("r");
    let chir: Vec<Complex64> = r
        .blk("chir_re")
        .iter()
        .zip(r.blk("chir_im"))
        .map(|(&re, &im)| Complex64::new(re, im))
        .collect();
    let out = xftr(
        rr,
        &chir,
        r.f("rmin"),
        r.f("rmax"),
        r.f("dr"),
        None,
        r.i("rw"),
        r.win(),
        r.f("qmax_out"),
        r.f("nfft") as usize,
    );
    check_close("xftr rwin", &out.rwin, r.blk("rwin"), 1e-12);
    check_close("xftr q", &out.q, r.blk("q"), 1e-9);
    check_close("xftr chiq_re", &out.chiq_re, r.blk("chiq_re"), 1e-9);
    check_close("xftr chiq_im", &out.chiq_im, r.blk("chiq_im"), 1e-9);
}
